<?php

/**
 * Incorpora la possibilitat de passar per paràmetre el criteri d'ordenació
 * Sobreescriu el hook "hook_views_query_alter"
 * Paràmetre 'sort' conté el criteri, p.ex. 'node_title'
 */
function teb_toolbox_views_query_alter(&$view, &$query) {
	// node_data_field_doc_data_publi_field_doc_data_publi_value
	if (isset ( $_GET ['sort'] )) {
		$query->orderby [0] = "{$_GET['sort']} {$_GET['sortor']}";
	}
}

/**
 * Utility to change the max length of a text field
 */
function teb_toolbox_change_text_field_max_length($field_name, $new_length) {
	$field_table = 'field_data_' . $field_name;
	$field_revision_table = 'field_revision_' . $field_name;
	$field_column = $field_name . '_value';

	// Alter value field length in fields table
	//db_query("ALTER TABLE `{$field_table}` CHANGE `{$field_column}` `{$field_column}` VARCHAR( {$new_length} )");
	// Alter value field length in fields revision table
	//db_query("ALTER TABLE `{$field_revision_table}` CHANGE `{$field_column}` `{$field_column}` VARCHAR( {$new_length} )");

	// Update field config with new max length
	$result = db_query("SELECT CAST(`data` AS CHAR(10000) CHARACTER SET utf8) FROM `field_config` WHERE field_name = '{$field_name}'");
	$config = $result->fetchField();
	$config_array = unserialize($config);
	$config_array['settings']['max_length'] = $new_length;
	$config = serialize($config_array);
	db_update('field_config')
	->fields(array('data' => $config))
	->condition('field_name', $field_name)
	->execute();
}

?>