function cercador_agenda_cercador_form_submit_back($form,&$form_state){
	
	/* Date formatting */
	if($form_state['values']['init_date']['month']<10)
	{
		$month_aux = "0";
	}
	if($form_state['values']['init_date']['day']<10)
	{
		$day_aux = "0";
	}
	$date = $form_state['values']['init_date']['year'].
			"-".$month_aux.$form_state['values']['init_date']['month'].
			"-".$day_aux.$form_state['values']['init_date']['day']."T00:00:00";
			
	/* End of date formatting */
	
	if(isset($form_state['values']['buscar']) and $form_state['values']['buscar']!=""){ //words to searchs its not empty
		
		$a_text = preg_split("[ ]", $form_state['values']['buscar']);
		
			/* Select event nodes with date greater equal than the form date 
			of the type specified type (curs, event) witch have the key words (using drupal search index)*/
			$query = "SELECT n.nid, field_map_mapa_marker_lat, field_map_mapa_marker_lng, field_map_mapa_data_id
			FROM {node n, search_index si, content_type_event cte} 
			WHERE n.nid = si.sid
				AND n.nid = cte.nid
				AND n.type ='event'";

			if($form_state['values']['tipus']!="tots")
			{
				$query.=" AND UPPER(cte.field_event_type_value) = UPPER('"._scape($form_state['values']['tipus'])."')";
			}

			$query.=" AND (si.word ='"._scape($a_text[0])."'";
			
			for($i=1;$i<sizeof($a_text);$i++)
			{
				$query.="OR si.word = '"._scape($a_text[$i])."'";
			}
	
			$query.=") ORDER BY cte.field_date_event_value ASC";	
		
	} else { //words to search is empty
		
		/* Select event nodes with date greater equal than the form date of the type specified type (curs, event)*/
		$query = "SELECT n.nid, field_map_mapa_marker_lat, field_map_mapa_marker_lng, field_map_mapa_data_id
			FROM {node n, content_type_event cte} 
			WHERE n.nid = cte.nid
				AND n.type ='event'
				AND '"._scape($date)."' <= cte.field_date_event_value";
				
		if($form_state['values']['tipus']!="tots")
		{
			$query.=" AND UPPER(cte.field_event_type_value) = UPPER('"._scape($form_state['values']['tipus'])."')";
		}
		$query.=" ORDER BY cte.field_date_event_value ASC";
		/* end of node selection*/
	
		
	}
	
	$result = db_query($query);
		
	$i=0;
	while ($res = db_fetch_array($result)){
		$node = node_load($res['nid']);
		$array[]=$node;
		$markers[$i]['marker'] = 'green';
		$markers[$i]['longitude'] = $res['field_map_mapa_marker_lng'];
		$markers[$i]['latitude']  = $res['field_map_mapa_marker_lat'];
		$markers[$i]['text']= _get_map_text($node);
		$i++;
		
	}
	
	$map = array(
		'id' => 'Mapa',           // id attribute for the map
		'width' => "95%",        // map width in pixels or %
		'height' => "400px",      // map height in pixels
		'behavior' => array(      // Various map behavior flags.
			'autozoom' => true					  
		),
		'markers' => $markers
		);
								
	$map = ekigmaps_create_map($map);	
	
	session_start();
	$_SESSION['search']=$array;
	$_SESSION['map'] = $map;
	$_SESSION['data']=$query;
	/*$_SESSION['form']=$form_state['values'];*/
	
}


function cercador_agenda_cercador_back($resultado=""){
  
  $return = drupal_get_form('cercador_agenda_cercador_form');
  if (!isset($_POST['form_id'])) {
		$results = cercador_agenda_cercador_form_submit();
  }  
  if(isset($_SESSION['search']))
  {
	if(sizeof($_SESSION['search'])>0)
	{
		print sizeof($_SESSION['search']);
		$nodes = $_SESSION['search'];
	
		if(isset($_SESSION['map'])){
				ekigmaps_add_header();
				$return.=$_SESSION['map'];
				echo "mapa out";
		}
		foreach($nodes as $node)
		{
			$return.="<p><a href='".base_path().$node->path."'>".$node->title."</a></p>";
			$return.="<p>".$node->field_date_event[0]['value']."</p>";
			$return.="<p>".$node->field_resum[0]['value']."</p>";
			//print "<p>".$node."</p>";
		}
	}
}

	print $_SESSION['data'];
	/*firep($_SESSION['form'],"form");*/
	unset($_SESSION['search']);
	unset($_SESSION['data']);
	/*unset($_SESSION['form']);  */
	unset($_SESSION['map']); 
  /*ASORT*/
  
  
  
  return $return;
}