<?php 

function xarxanet_revisions_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL){
  
  if ($op == 'update' && $node->revision == 1) {
    $aids = _trigger_get_hook_aids('nodeapi', 'revision');
    $context = array(
      'hook' => 'nodeapi',
      'op' => $op,
      'node' => $node,
    );
    actions_do(array_keys($aids), $node, $context);
  }
}

function xarxanet_revisions_hook_info() {
  return array(
    'xarxanet_revisions' => array(
      'nodeapi' => array(
        'revision' => array(
          'runs when' => t('After node revision is created'),
        ),
      ),
    ),
  );
}

function xarxanet_revisions_action_info() {
  return array(
    'xarxanet_revisions_send_mail_action' => array(
      'description' => t('Send email on revision creation'),
      'type' => 'node',
      'configurable' => FALSE,
      'hooks' => array('nodeapi' => array('revision')),
      ),
  );
}

function xarxanet_revisions_send_mail_action(&$object, $context = array()){
  $creador = user_load($object->uid);

  $revision_log = $object->log;
  $title = $object->title;
  $url = url($object->path,array('absolute'=>TRUE));

  $to = $creador->mail;
  $titulo = 'Revisió del contingut publicat a xarxanet.org';
  $mensaje ="<html><head></head><body>Benvolguts/des,<br/><br/>
Des de la coordinació de continguts de xarxanet.org hem revisat el contingut publicat <a href=\"".$url."\">".$title."</a> incloent les següents modificacions:<br/><br/>

".$revision_log."<br/><br/>

Salutacions,<br/><br/>

Coordinació de continguts de xarxanet.org<br/>
Entitats i voluntaris per un món millor.<br/>
93 410 16 02 (extensió 3513)<br/>
xarxanetadmin@xarxanet.org</body></html>";

  $cabeceras = 'From: xarxanetadmin@xarxanet.org' . "\r\n" .
    'Reply-To: xarxanetadmin@xarxanet.org' . "\r\n" .
    'X-Mailer: PHP/' . phpversion()."\r\n";
  $cabeceras .= 'MIME-Version: 1.0'."\r\n";
  $cabeceras .= 'Content-Type: text/html; charset=ISO-8859-1'."\r\n";
    
  mail($to, $titulo, $mensaje, $cabeceras);
}