<?php

/**
 * theme function that renders the HTML for the tags
 * @ingroup themable
 */
function theme_equi_tagadelic_weighted($terms) {
  $output = '';
  foreach ($terms as $term) {
    $output .= l($term->name, "recursos_tag/".$term->name, array('attributes' => array('class' => "tagadelic level$term->weight", 'rel' => 'tag'))) ." \n";
  }
  return $output;
}

/**
 * Implementation of hook_theme
 */
function equi_tagadelic_theme() {
  return array(
    'equi_tagadelic_weighted' => array('arguments' => array('terms' => NULL))
  );
}
