<?php

// $Id$
function searchbuilder_perm(){
  return array('admin searchbuilder','build searches');
}

function searchbuilder_menu(){
  $items = array();
  
  $items['cerca/build'] = array(
    'page callback' => 'searchbuilder_cerca_build_page',
    'access arguments' => array('build searches'),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

function searchbuilder_cerca_build_page(){
  $searchterm = $_GET['searchterm'];
  drupal_goto('search/apachesolr_search/'.$searchterm);
  
  return "This should be never seen!";
}