<?php

/**
 * Implements hook_menu() 
 * 
 * @return $items
 */

function webform_mailing_menu() {

  $items['node/%webform_menu/webform/mailing'] = array(
    'title' => t('Webform mailing'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('webform_mailing_form', 1),
    'access callback' => 'webform_node_update_access',
    'access arguments' => array(1),
    'file' => 'webform_mailing.admin.inc',
    'weight' => 6,
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}
