<?php
// $Id$
/**
 */
function aux_functions_nodeapi(&$node, $op, $teaser, $page) {
	switch ($op) {
		// The 'view' operation means the node is about to be displayed.
		case 'validate' :
			
			if (substr ( $node->type, 0, 6 ) == "recurs") {
				
				$continguts = 0;
				$subtitols = 0;
				foreach ( $node->field_continguts as $contingut ) {
					if ($contingut ['value'] != "") {
						$continguts ++;
					}
				}
				foreach ( $node->field_subtitols as $subtitol ) {
					if ($subtitol ['value'] != "") {
						$subtitols ++;
					}
				}
				
				if ($continguts != $subtitols) {
					form_set_error ( "error", t ( "El n&uacute;mero de subtitols i el n&uacute;mero de continguts ha de ser igual" ), FALSE );
				}
			}
			break;
		
		case 'update' :
		case 'submit' :
			
			if ((substr ( $node->type, 0, 7 ) == "noticia") || (substr ( $node->type, 0, 6 ) == "recurs")) {
				if ($node->field_dpp [0] ['value'] == "Destacat principal a portada") {
					$query = "Select n.nid from content_field_dpp cfdpp, node n 
								where cfdpp.nid = n.nid ";
					
					if ((substr ( $node->type, 0, 7 ) == "noticia")) {
						$query .= " AND SUBSTR(n.type,1,7)  = 'noticia' ";
					} else {
						$query .= " AND SUBSTR(n.type,1,6)  = 'recurs' ";
					}
					$query .= " AND cfdpp.field_dpp_value = 'Destacat principal a portada' ORDER BY n.changed DESC";
					$result = db_query ( $query );
					// drupal_set_message("Query $query");
					while ( $row = db_fetch_array ( $result ) ) {
						$id = $row ["nid"];
						$query = "UPDATE content_field_dpp SET field_dpp_value = 'No destacat principal a portada' WHERE nid=$id";
						
						db_query ( $query );
						// drupal_set_message("Se hubiera modificado el id $id");
					}
				}
				if ($node->field_dsp [0] ['value'] == "Destacat secundari a portada") {
					$query = "Select n.nid from content_field_dsp cfdsp, node n 
								where cfdsp.nid = n.nid ";
					
					if ((substr ( $node->type, 0, 7 ) == "noticia")) {
						$query .= " AND SUBSTR(n.type,1,7)  = 'noticia' ";
					} else {
						$query .= " AND SUBSTR(n.type,1,6)  = 'recurs' ";
					}
					$query .= " AND cfdsp.field_dsp_value = 'Destacat secundari a portada' ORDER BY n.created DESC";
					
					$result = db_query ( $query );
					$i = 1;
					
					while ( $row = db_fetch_array ( $result ) ) {
						$id = $row ["nid"];
						if ($node->nid != $id) {
							if ($i > 1) {
								$query = "UPDATE content_field_dsp SET field_dsp_value = 'No destacat secundari a portada' WHERE nid=$id";
								db_query ( $query );
							} else {
								$i ++;
							}
						}
						// drupal_set_message("Se hubiera modificado el id $id");
					}
				}
				if ($node->field_dpp_portal [0] ['value'] == "Destacat principal portal") {
					
					$type = $node->type;
					$query = "Select n.nid from content_field_dpp_portal cfdpp_portal, node n 
								where cfdpp_portal.nid = n.nid 
									AND n.type  = '$type' 
									AND cfdpp_portal.field_dpp_portal_value = 'Destacat principal portal' ORDER BY n.changed DESC";
					$result = db_query ( $query );
					
					while ( $row = db_fetch_array ( $result ) ) {
						$id = $row ["nid"];
						$query = "UPDATE content_field_dpp_portal SET field_dpp_portal_value = 'No destacat principal portal' WHERE nid=$id";
						
						db_query ( $query );
					}
				}
				if ($node->field_dsp_portal [0] ['value'] == "Destacat secundari portal") {
					$type = $node->type;
					$query = "Select n.nid from content_field_dsp_portal cfdsp_portal, node n 
									where cfdsp_portal.nid = n.nid 
										AND n.type  = '$type' 
										AND cfdsp_portal.field_dsp_portal_value = 'Destacat secundari portal' 
										ORDER BY n.created DESC";
					
					$result = db_query ( $query );
					$i = 1;
					
					while ( $row = db_fetch_array ( $result ) ) {
						$id = $row ["nid"];
						if ($node->nid != $id) {
							if ($i > 1) {
								$query = "UPDATE content_field_dsp_portal SET field_dsp_portal_value = 'No destacat secundari portal' WHERE nid=$id";
								db_query ( $query );
							} else {
								$i ++;
							}
						}
					}
				}
			}
			break;
	}
}
function aux_functions_theme() {
	return array (
			'sidebar_noticia' => array (
					'template' => $base_path . path_to_theme () . 'sidebar_noticia',
					'arguments' => array (
							'autor' => null,
							'imatges' => null,
							'links' => null,
							'entitats' => null 
					) 
			),
			'noticia' => array (
					'template' => $base_path . path_to_theme () . 'noticia',
					'arguments' => array (
							'terms' => null,
							'imatge_petita' => null,
							'imatge_petita_alt' => null,
							'resum' => null,
							'contingut' => null,
							'autor' => null,
							'imatges' => null,
							'unpublished' => null,
							'links' => null,
							'service_links' => null,
							'entitats' => null,
							'data_modificada' => null 
					)
					 
			),
			'recurs' => array (
					'template' => $base_path . path_to_theme () . 'noticia',
					'arguments' => array (
							'terms' => null,
							'imatge_petita' => null,
							'imatge_petita_alt' => null,
							'imatges' => null,
							'resum' => null,
							'titols' => null,
							'continguts' => null,
							'autor' => null,
							'enllacos' => null,
							'unpublished' => null,
							'links' => null,
							'service_links' => null,
							'votacio' => null 
					)
					 
			),
			'sidebar_recurs' => array (
					'template' => $base_path . path_to_theme () . 'sidebar-recurs',
					'arguments' => array (
							'autor' => null,
							'enllacos' => null,
							'links' => null,
							'votacio' => null,
							'imatges' => null 
					)
					 
			),
			'event' => array (
					'template' => $base_path . path_to_theme () . 'event',
					'arguments' => array (
							'terms' => null,
							'imatge_petita' => null,
							'imatge_petita_alt' => null,
							'resum' => null,
							'contingut' => null,
							'unpublished' => null,
							'links' => null,
							'service_links' => null,
							'ambits' => null,
							'data' => null,
							'organitzador' => null,
							'adreca_org' => null,
							'adreca' => null,
							'ciutat' => null,
							'telefon' => null,
							'web' => null,
							'correu' => null,
							'tipus' => null,
							'mapa' => null 
					) 
			),
			'sidebar_event' => array (
					'template' => $base_path . path_to_theme () . 'sidebar_event',
					'arguments' => array (
							'adreca' => null,
							'organitzador' => null,
							'ambits' => null,
							'mapa' => null,
							'links' => null 
					) 
			) 
	);
}


