<?php

// $Id$

function exim_perm(){
  return array('edit exim');
}

function exim_menu(){
  $items = array();
  $items['excelimport'] = array(
    'title' => 'Importar Excel',
    'page callback' => 'exim_main_page',
    'access arguments' => array('admin exim'),
    'menu_name' => 'navigation',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function exim_main_page(){
  
  /*module_load_include('php','exim','Excel/reader');
  
  // ExcelFile($filename, $encoding);
  $data = new Spreadsheet_Excel_Reader();
  // Set output Encoding.
  $data->setOutputEncoding('CP1251');
  $data->read('sites/all/modules/excelimport/usuarios.xls');
  error_reporting(E_ALL ^ E_NOTICE);
  for ($i = 2; $i <= $data->sheets[0]['numRows']; $i++) {
    //Recorrem fila a fila
    $options['name'] = $data->sheets[0]['cells'][$i][1];
    $options['mail'] = $data->sheets[0]['cells'][$i][2];
    $options['init'] = $data->sheets[0]['cells'][$i][2];
    $options['status'] = 1;
    $options['roles'][3] = 'Newslettermen';
    
    $options['pass'] = user_password();
    $user = user_save($account,$options);
  }

  $idnews = db_result(db_query("SELECT idnews FROM {newsletters}"));
  $resparts = db_query("SELECT p.idpart FROM {parts} p, {partsconfig} pc WHERE p.idnews = %d AND p.idpart = pc.idpart AND pc.tipus = 'subscription'",$idnews);
  while($res = db_fetch_array($resparts)){
    $parts[$res['idpart']] = '';
  }
  foreach($parts as $key => $part){
    $partuser[$key] = '';
  }
  
  $data2 = new Spreadsheet_Excel_Reader();
  $data2->setOutputEncoding('CP1251');
  $data2->read('sites/all/modules/excelimport/subs.xls');
  error_reporting(E_ALL ^ E_NOTICE);
 
  for ($i = 4; $i <= $data2->sheets[0]['numRows']; $i++) {
    $array['mail'] = $data2->sheets[0]['cells'][$i][2];
    $mail2 = $data2->sheets[0]['cells'][$i+1][2];
    $user = user_load($array);
    $j = 3;
    if($mail2 != $array['mail']){
      foreach($parts as $key => $part){
        if($data2->sheets[0]['cells'][$i][$j]==1){
          $partuser[$key] = $key;
        }
        $j++;
      }
    } else {
      foreach($parts as $key => $part){
        if($data2->sheets[0]['cells'][$i][$j]==1 || $data2->sheets[0]['cells'][$i+1][$j]==1){
          $partuser[$key] = $key;
        }
        $j++;
      }
      $i++;
    }
    $result = db_query("UPDATE {users_prefs} SET preferences = '%s' WHERE uid = %d AND idnews = %d",serialize($partuser),$user->uid,$idnews);
  }*/
  
  $result = db_query("SELECT u.uid FROM {users} u, {role} r, {users_roles} ur WHERE u.uid = ur.uid AND ur.rid = r.rid AND r.name = 'subscriptor'");
  while($user = db_fetch_array($result)){
    user_delete($edit,$user['uid']);
  }

  return "Ah!";
}
        