<?php

function xarxanet_widgets_menu() {	
	$items = array();

  $items['widgets'] = array(
    'title' => "Noticies ambientals",
    'description' => "Widget per les noticies",
    'page callback' => 'xarxanet_widgets_content',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['widgets/crear'] = array(
    'title' => "Creador de Widgets",
    'description' => "Formulari per crear Widgets",
    'page callback' => 'drupal_get_form',
	'page arguments' => array('xarxanet_widgets_create'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}
function xarxanet_widgets_content($id, $item) {
	if(!xarxanet_widgets_validate($id, $item)){
		$json = "{'content':'Arguments no vàlids'}";
		echo "json_callback($json, 0)";
		die;
	}
	$header="<div id=\"xxnet-header\"><div class=\"xxnet-header-inner\"><a href=\"".xarxanet_widgets_base()."\"><img src=\"".xarxanet_widgets_base().drupal_get_path('module','xarxanet_widgets')."/xxnet.png"."\" title=\"Logo Xarxanet\" alt=\"Logo Xarxanet\"/></a></div><div class=\"xxnet-header-dec\"></div></div>";
	$bottom= "<div id=\"xxnet-bottom\"><div id=\"xxnet-bottom-inner\"></div>";
	$output="";
	$selected = explode("c",$item);
	
	$types[1]['title']="Ambiental";
	$types[1]['name']="noticia_ambiental";
	
	$types[2]['title']="Comunitari";
	$types[2]['name']="noticia_comunitari";
	
	$types[3]['title']="Cultural";
	$types[3]['name']="noticia_cultural";
	
	$types[4]['title']="Internacional Català";
	$types[4]['name']="noticia_internacional_cat";
	
	$types[12]['title']="Internacional Anglès";
	$types[12]['name']="noticia_internacional_ang";
	
	$types[13]['title']="Internacional Castellà";
	$types[13]['name']="noticia_internacional_esp";
	
	$types[14]['title']="Finançaments"; 
	$types[14]['name']="financament";
	
	$types[5]['title']="Social";
	$types[5]['name']="noticia_social";
	
	$types[6]['title']="Econòmic";	
	$types[6]['name']="noticia_economic";
	$types[6]['recurs']="recurs_economic";
	
	$types[7]['title']="Formació";
	$types[7]['name']="noticia_formacio";
	$types[7]['recurs']="recurs_formacio";
	
	$types[8]['title']="Informàtic";
	$types[8]['name']="noticia_informatic";
	$types[8]['recurs']="recurs_informatic";
	
	$types[9]['title']="Jurídic";
	$types[9]['name']="noticia_juridic";
	$types[9]['recurs']="recurs_juridic";
	
	$types[10]['title']="Projectes";
	$types[10]['name']="noticia_projectes";
	$types[10]['recurs']="recurs_projectes";
	
	$types[11]['title']="General";
	$types[11]['name']="noticia_general";
	$types[11]['recurs']="recurs_general";
	
	foreach($selected as $key=>$selection){
		$output .= xarxanet_widgets_section_header($types[$selection]['title']);
		$view = views_get_view("widget");
		if(isset($types[$selection]['recurs'])){
			$view->preview("block_2", array($types[$selection]['name']));
			$output .= xarxanet_widgets_render_view($view);
			$view = views_get_view("widget");
			$view->preview("block_2", array($types[$selection]['recurs']));
			$output .= xarxanet_widgets_render_view($view);
		}else if($types[$selection]['name']=="financament"){	
			$view->preview("block_3", array($types[$selection]['name']));
			$output .= xarxanet_widgets_render_view($view, "financament");
		}else{	
			$view->preview("block_1", array($types[$selection]['name']));
			$output .= xarxanet_widgets_render_view($view);
		}
	}
	$output = "<div id=\"xxnet-wrapper\">".$header."<div id=\"xxnet-container\"><div id=\"xxnet-container-inner\"><div class=\"xxnet-inner\">".$output."</div></div></div>".$bottom."</div>";
	$output = xarxanet_widgets_clean($output);
	$json = "{'content':'$output'}";
	echo "json_callback($json, $id)";
	die;
}
/*
* The sytle has been hard coded to get better performance if the widgets is called by several websites 
* Return the final encoded html string
*/
function xarxanet_widgets_render_view(&$view, $type="general"){
	
	$title = "";
	$field_imatge_petita_fid = "";
	//$field_resum_value = "";
	$output = "";
	if($type=="financament"){
		foreach($view->result as $id=>$result){
			$path =  $view->render_field('field_enllac_financament_value', $id);
			$title = "<div>".l($view->render_field('title', $id), $path, array("html"=>true))."</div>";
			$output .=	"<div class=\"xxnet-item\">".$title."</div>";			
		}
	}else{
		foreach($view->result as $id=>$result){
			$path =  url("node/{$view->result[$id]->nid}", array('absolute' => TRUE)); 
			$title = "<div>".l($view->render_field('title', $id), $path, array("html"=>true))."</div>";
			$field_imatge_petita_fid = "<div class=\"xxnet-pic\">".l($view->render_field('field_imatge_petita_fid', $id), $path, array("html"=>true))."</div>";
			//$field_resum_value = "<div>".$view->render_field('field_resum_value',$id)."</div>";
			//$output .=	"<div class=\"xxnet-item\">".$field_imatge_petita_fid.$title.$field_resum_value."</div>";
			$output .=	"<div class=\"xxnet-item\">".$field_imatge_petita_fid.$title."</div>";
			
		}
	}
	return $output;
}
function xarxanet_widgets_clean($string){
   
    return str_replace(array('<', '>', '&','"',"'","\r","\r\n","\n"), array('\u003c', '\u003e', '\u0026','\u0022','\u0027', "","",""), $string);
}
function xarxanet_widgets_base(){
	return ((empty($_SERVER['HTTPS'])||$_SERVER['HTTPS']=="off")?"http://":"https://").$_SERVER['HTTP_HOST'].base_path();
}

function xarxanet_widgets_create($form_state){

	$form = array();
	
	
		
	
	$form['height'] = array(
		'#type' => 'textfield',
		'#title' => t('Alçada', null, "ca"),
		'#required' => TRUE,
		'#default_value' => $form_state['values']['height']?$form_state['values']['height']:'400px',
		'#description' => t('Introdueix la mida en format 400px, 2em o 50% (Valor de exemple)',null,"ca"),
	);
	$form['width'] = array(
		'#type' => 'textfield',
		'#title' => t('Amplada', null, "ca"),
		'#required' => TRUE,
		'#default_value' => $form_state['values']['width']?$form_state['values']['width']:'100%',
		'#description' => t('Introdueix la mida en format 200px o 100% (Valor de exemple)',null,"ca"),
	);
	$form['background'] = array(
		'#type' => (module_exists('colorpicker') ? 'colorpicker_' : '') . 'textfield',
		'#title' => t('Color de fons', null, "ca"),
		'#required' => TRUE,
		'#default_value' => $form_state['values']['background']?$form_state['values']['background']:'#E2E1DF',
	);
	$form['header_color'] = array(
		'#type' => (module_exists('colorpicker') ? 'colorpicker_' : '') . 'textfield',
		'#title' => t('Color les lletres de les capçaleres', null, "ca"),
		'#required' => TRUE,
		'#default_value' => $form_state['values']['header_color']?$form_state['values']['header_color']:'#303030',
	);
	
	$form['options_noticies']= array(
		'#type' => 'checkboxes',
		'#title' => t('Tria els continguts a mostrar', null, "ca"),
		'#required' => TRUE,
		'#options' => array(
			'11' => t('General',null,"ca"), 
			'14' => t('Finançaments',null,"ca"), 
			'1' => t('Ambiental',null,"ca"), 
			'2' => t('Comunitari',null,"ca"), 
			'3' => t('Cultural',null,"ca"), 
			'4' => t('Internacional Català',null,"ca"), 
			'12' => t('Internacional Anglès',null,"ca"),
			'13' => t('Internacional Castellà',null,"ca"),
			'5' => t('Social',null,"ca"), 
			'6' => t('Econòmic',null,"ca"), 
			'7' => t('Formació',null,"ca"), 
			'8' => t('Informàtic',null,"ca"), 
			'9' => t('Jurídic',null,"ca"), 
			'10' => t('Projectes',null,"ca"), 
			),
		'#default_value' => $form_state['values']['options_noticies']?$form_state['values']['options_noticies']:array(),
		);
	
	$form['submit']=array(
		'#type' => 'submit',
		'#value' => 'Crear',		
	);
	if (!empty($form_state['storage']['step'])) {
		$form = array_merge(xarxanet_widgets_show($form_state),$form);
	}
	
	
	return $form;

}
//TODO validate values
function xarxanet_widgets_show($form_state){
	
	$height = $form_state['values']['height'];
	$width = $form_state['values']['width'];
	$background = str_replace("#","",$form_state['values']['background']);
	$header_color = str_replace("#","",$form_state['values']['header_color']);
	
	$selected = $form_state['values']['options_noticies'];
	$content = "";
	
	foreach($selected as $key=>$value){
		if($key==$value){
			$content .= "c".$key;
		}
	}
	$content  = substr($content,1);
	
	$script = "<script id=\"xxnet-widget\" src=\"".xarxanet_widgets_base().drupal_get_path('module','xarxanet_widgets')."/xarxanet_widgets.js\"></script>
	<script>new xxnetWidget({content:'$content',height:'$height',width:'$width',background:'$background',header_color:'$header_color'}).start(); </script>";
	
	$form['widget_preview']=array(
		'#value' => ($script),
	);
	$form['info']=array(
		'#value' => "<br/><br/><p>".t("Copia aquest codi a qualsevol punt de la teva web o blog",null,"ca")."</p>",		
	);
	$form['widget']=array(
		'#value' => "<pre>".htmlspecialchars($script)."</pre><br/><br/>",		
	);
	return $form;
}
function xarxanet_widgets_create_submit($form, &$form_state){	
	$form_state['storage']['step'] = "submitted";
	$form_state['storage']['values']['submitted'] = $form_state['values'];
	
}

function xarxanet_widgets_section_header($section){
	return "<div class=\"xxnet-header-section\">".$section."</div>";
}

function xarxanet_widgets_validate($id, $item){
	$validate_id = preg_match("/^[0-9]+$/",$id)==1;
	$validate_item = preg_match("/^([0-9]+){1}(c[0-9]+)*$/",$item)==1;	
	//return $validate_id && $validate_item;
	return true;
}