<?php

define("KEY", "9f44c9f651023f2799b0e72acdaf28e3");

/**
 * Implements hook_xmlrpc().
 *
 * Provides Drupal with an array to map XML-RPC callbacks to existing functions.
 * These functions may be defined in other modules. The example implementation
 * defines specific functions for the example services.
 *
 * Note: Drupal's built-in XML-RPC server already includes several methods by
 * default:
 *
 * Service dicovery methods:
 * - system.listMethods: return a list of the methods the server has, by name.
 * - system.methodSignature: return a description of the argument format a
 * - system.methodHelp: returns a text description of a particular method.
 *   particular method expects.
 *
 * Other:
 * - system.multicall: perform several method calls in a single xmlrpc request.
 * - system.getCapabilities: determine if a given capability is supported.
 *
 * The methods defined by hook_xmlrpc() will be added to those provided by
 * default by Drupal's XML-RPC server.
 *
 * @see hook_xmlrpc()
 */
function simplenews_service_xmlrpc() {
  $methods[] = array(
    'simplenews_service.subscribe',
    '_simplenews_service_server_subscribe',
    array('int', 'string', 'string', 'int'),
    t('Subscribe an e-mail adress to a newsletter'),
  );
  $methods[] = array(
    'simplenews_service.unsubscribe',
    '_simplenews_service_server_unsubscribe',
    array('int', 'string', 'string', 'int'),
    t('Unsubscribe an e-mail adress from a newsletter'),
  );
  return $methods;
}

/**
 * This is the callback for the simplenews_service.add method.
 *
 * Sum the two arguments and return value or an error if the result is out of
 * the configured limits.
 *
 * @param int|float $num1
 *   The first number to be summed.
 * @param int|float $num2
 *   The second number to be summed.
 *
 * @return int|float
 *   The sum of the arguments, or error if it is not in server defined bounds.
 *
 * @see xmlrpc_error()
 */
function _simplenews_service_server_subscribe($key, $mail, $tid) {
	if ($key == KEY) {
		$result = simplenews_subscribe_user($mail, $tid);
		return $result	;
	} else {
		return xmlrpc_error(10001, t('Invalid key'));
	}
}

/**
 * This is the callback for the simplenews_service.subtract xmlrpc method.
 *
 * Return the difference of the two arguments, or an error if the result is out
 * of the configured limits.
 *
 * @param int|float $num1
 *   First number
 * @param int|float $num2
 *   Second number
 *
 * @return int|float
 *   The difference of the two arguments, or error if it is not in server
 *   defined bounds.
 *
 * @see xmlrpc_error()
 */
function _simplenews_service_server_unsubscribe($key, $mail, $tid) {
	if ($key == KEY) {
		$result = simplenews_unsubscribe_user($mail, $tid);
		return $result	;
	} else {
		return xmlrpc_error(10001, t('Invalid key'));
	}
}


?>