<?php

// Set some helper constants.
define('JOB_OFFER_URL', 'add/oferta-feina');

/**
 * Implements hook_init().
 */

function tothomweb_jobs_init() {
	drupal_add_js(drupal_get_path('module', 'tothomweb_jobs') . '/js/tothomweb_jobs.js');
}

function tothomweb_jobs_preprocess_html(&$vars) {
	if (current_path() == JOB_OFFER_URL) {
		$vars['head_title'] = 'Publica la teva oferta';
		$vars['classes_array'][] = 'page-add-job-offer';
	}
}

/**
 * Implements hook_menu().
 *
 * @return  $items
 */
function tothomweb_jobs_menu() {
	$items[JOB_OFFER_URL] = array(
		'title' => 'Publica la teva oferta',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('tothomweb_jobs_form'),
		'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
	);
	return $items;
}

/**
 * Implements hook_form().
 */
function tothomweb_jobs_form($form, &$form_state) {

  $form['container'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'class' => array('container'),
    ),
  );

  $form['container']['grid'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'class' => array('jobs_offer_form_grid'),
    ),
  );

  $form['container']['grid']['mandatory'] = array(
    '#type' => 'markup',
    '#markup' => '<p class="mandatory">' . t("El camps amb un asterisc (<span>*</span>) son obligatoris."). '</p>',
    '#prefix' => '<div class="job_offer_item job_offer_mandatory">',
    '#suffix' => '</div>',
  );

  $form['container']['grid']['job_offer_title'] = array(
    '#title' => t("Títol de l'oferta de feina"),
    '#type' => 'textfield',
    '#maxlength' => '255',
    '#default_value' => isset($form_state['values']['job_offer_title']) ? $form_state['values']['job_offer_title'] : '',
    '#required' => true,
    '#prefix' => '<div class="job_offer_item job_offer_title">',
    '#suffix' => '</div>',
  );

  $form['container']['grid']['job_offer_entity'] = array(
    '#title' => t("Nom de l'entitat"),
    '#type' => 'textfield',
    '#maxlength' => '255',
    '#default_value' => isset($form_state['values']['job_offer_entity']) ? $form_state['values']['job_offer_entity'] : '',
    '#description' => t("Indica el nom de l'entitat que ofereix aquesta oferta de feina."),
    '#required' => true,
    '#prefix' => '<div class="job_offer_item job_offer_entity">',
    '#suffix' => '</div>',
  );

  $form['container']['grid']['job_offer_mail'] = array(
    '#title' => t('Correu electrònic'),
    '#type' => 'textfield',
    '#maxlength' => '127',
    '#default_value' => isset($form_state['values']['job_offer_mail']) ? $form_state['values']['job_offer_mail'] : '',
    '#required' => true,
    '#prefix' => '<div class="job_offer_item job_offer_mail">',
    '#suffix' => '</div>',
  );

  $form['container']['grid']['job_offer_phone'] = array(
    '#title' => t('Telèfon'),
    '#type' => 'textfield',
    '#maxlength' => '16',
    '#default_value' => isset($form_state['values']['job_offer_phone']) ? $form_state['values']['job_offer_phone'] : '',
    '#description' => t("Indica un telèfon de contacte, sense espais ni símbols."),
    '#prefix' => '<div class="job_offer_item job_offer_phone">',
    '#suffix' => '</div>',
  );

  $form['container']['grid']['job_offer_location'] = array(
    '#title' => t('Població'),
    '#type' => 'textfield',
    '#maxlength' => '127',
    '#default_value' => isset($form_state['values']['job_offer_location']) ? $form_state['values']['job_offer_location'] : '',
    '#required' => true,
    '#prefix' => '<div class="job_offer_item job_offer_location">',
    '#suffix' => '</div>',
  );

  $form['container']['grid']['job_offer_date'] = array(
    '#title' => t('Termini'),
    '#type' => 'textfield',
    '#maxlength' => '16',
    '#default_value' => isset($form_state['values']['job_offer_date']) ? $form_state['values']['job_offer_date'] : '',
    '#description' => t("Indica la data límit de convocatòria d'aquesta oferta."),
    '#required' => true,
    '#prefix' => '<div class="job_offer_item job_offer_date">',
    '#suffix' => '</div>',
  );

  $form['container']['grid']['managed_file'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'class' => array('job_offer_item job_offer_attached'),
    ),
  );

  $job_offer_attached_description  = "<p>";
  $job_offer_attached_description .= t("Afegeix un document amb informació addicional sobre l'oferta de feina.");
  $job_offer_attached_description .= "<br/>";
  $job_offer_attached_description .= t("Només es permeten arxius en format PDF, de 3 MB com a màxim.");
  $job_offer_attached_description .= "</p>";

  $form['container']['grid']['managed_file']['job_offer_attached'] = array(
    '#title' => t('Informació addicional adjunta'),
    '#type' => 'managed_file',
    '#default_value' => isset($form_state['values']['job_offer_attached']) ? $form_state['values']['job_offer_attached'] : '',
    '#description' => $job_offer_attached_description,
    '#upload_location' => 'public://job_offers/',
    '#upload_validators' => array(
      'file_validate_extensions' => array('pdf'),
      'file_validate_size' => array(3 * 1024 * 1024) // 3 MB
    ),
  );

  /**
   * There's a well-known unfixed issue with the '#default_value' of 'text_format' elements.
   * It doesn't render the value at all, when comes from $form_state.
   *
   * @see   https://tinyurl.com/yf3hnbjs
   */

  $form['container']['grid']['job_offer_description'] = array(
    '#title' => t('Descripció del lloc de feina'),
    '#type' => 'text_format',
    '#format' => '1',
    '#default_value' => isset($form_state['values']['job_offer_description']) ? $form_state['values']['job_offer_description']['value'] : '',
    '#description' => t("Indica els aspectes relacionats amb el lloc de feina."),
    '#required' => true,
    '#prefix' => '<div class="job_offer_item job_offer_description">',
    '#suffix' => '</div>',
  );

  $form['container']['grid']['job_offer_requirements'] = array(
    '#title' => t('Requisits'),
    '#type' => 'text_format',
    '#format' => '1',
    '#default_value' => isset($form_state['values']['job_offer_requirements']) ? $form_state['values']['job_offer_requirements']['value'] : '',
    '#description' => t("Indica els requisits mínims que ha de complir el candidat que opti a aquesta oferta de feina."),
    '#required' => true,
    '#prefix' => '<div class="job_offer_item job_offer_requirements">',
    '#suffix' => '</div>',
  );

  $form['container']['grid']['job_offer_conditions'] = array(
    '#title' => t('Condicions'),
    '#type' => 'text_format',
    '#format' => '1',
    '#default_value' => isset($form_state['values']['job_offer_conditions']) ? $form_state['values']['job_offer_conditions']['value'] : '',
    '#description' => t("Indica les condicions d'aquesta oferta de feina com la jornada laboral oferida, el salari, etc."),
    '#required' => true,
    '#prefix' => '<div class="job_offer_item job_offer_conditions">',
    '#suffix' => '</div>',
  );

  $form['container']['grid']['job_offer_submit'] = array(
    '#value' => t('Publicar la oferta'),
    '#type' => 'submit',
    '#prefix' => '<div class="job_offer_item job_offer_submit">',
    '#suffix' => '</div>',
  );

	return $form;
}

/**
 * Implements hook_form_validate().
 */
function tothomweb_jobs_form_validate($form, &$form_state) {
  $values = $form_state['values'];
  // Title
  if ($values['job_offer_title'] === '') {
    form_set_error('job_offer_title', t("El títol de l'oferta de feina és obligatori."));
  }
  // Entity name
  if ($values['job_offer_entity'] === '') {
    form_set_error('job_offer_entity', t("El nom de l'entitat és obligatori."));
  }
  // Mail
  if ($values['job_offer_mail'] === '') {
    form_set_error('job_offer_mail', t("L'adreça electrònica és obligatòria."));
  }
  else {
    if (!filter_var($values['job_offer_mail'], FILTER_VALIDATE_EMAIL)) {
      form_set_error('job_offer_mail', t("El format de l'adreça electrònica no és vàlid."));
    }
  }
  // Phone
  if (!is_numeric($values['job_offer_phone'])) {
    form_set_error('job_offer_phone', t("El telèfon només pot contenir números, sense espais, guions o altres símbols."));
  }
  // Location
  if ($values['job_offer_location'] === '') {
    form_set_error('job_offer_location', t("La població és obligatòria."));
  }
  // Date
  if ($values['job_offer_date'] === '') {
    form_set_error('job_offer_date', t("La data del termini és obligatòria."));
  }
  else {
    if (!preg_match("/^(0[1-9]|[1-2][0-9]|3[0-1])-(0[1-9]|1[0-2])-[0-9]{4}$/", $values['job_offer_date'])) {
      form_set_error('job_offer_date', t("La data del termini ha de tenir el format 'DD-MM-AAAA'."));
    }
  }
  // Description
  if ($values['job_offer_description'] === '') {
    form_set_error('job_offer_description', t("El camp descripció del lloc de feina és obligatori."));
  }
  // Requirements
  if ($values['job_offer_requirements'] === '') {
    form_set_error('job_offer_requirements', t("El camp requisits és obligatori."));
  }
  // Conditions
  if ($values['job_offer_conditions'] === '') {
    form_set_error('job_offer_conditions', t("El camp condicions del lloc de feina és obligatori."));
  }
}

/**
 * Implements hook_form_submit().
 */
function tothomweb_jobs_form_submit($form, &$form_state) {
  global $user;
  $author = user_load($user->uid);
  $values = $form_state['values'];
  // Set the roles that can publish job offers without approval
  $skip_moderation_roles = array(
    '3' => 'Entitat promotora ambiental',
    '5' => 'Entitat promotora projectes',
    '6' => 'Entitat promotora events',
    '9' => 'Entitat promotora social',
    '11' => 'Entitat promotora comunitari',
    '13' => 'Entitat promotora cultural',
    '15' => 'Entitat promotora internacional',
    '17' => 'Entitat promotora formacio',
    '18' => 'Entitat promotora juridic',
    '19' => 'Entitat promotora economic',
    '20' => 'Entitat promotora informatic',
    '22' => 'Entitat administradora',
  );
  // Set the node status value depending on the current user role
  $status = (user_has_roles($skip_moderation_roles)) ? 1 : 0;
  // Format 'job_offer_date' as datetime
  $timestamp = strtotime($values['job_offer_date']);
  $job_offer_datetime = date('Y-m-d H:i:s', $timestamp);
  // Create the new node
  $node = new stdClass();
  $node->uid = $author->uid;
  $node->type = 'job_offer';
  node_object_prepare($node);
  $node->title = $values['job_offer_title'];
  $node->status = $status;
  $node->promote = 0;
  $node->sticky = 0;
  $node->language = 'ca';
  $node->created  = time();
  $node->changed  = time();
  $node->field_job_offer_entity['und'][0]['value'] = $values['job_offer_entity'];
  $node->field_job_offer_mail['und'][0]['value'] = $values['job_offer_mail'];
  $node->field_job_offer_phone['und'][0]['value'] = $values['job_offer_phone'];
  $node->field_job_offer_location['und'][0]['value'] = $values['job_offer_location'];
  $node->field_job_offer_date['und'][0]['value'] = $job_offer_datetime;
  $node->field_job_offer_attached['und'][0]['display'] = 0;
  $node->field_job_offer_attached['und'][0]['fid'] = $values['job_offer_attached'];
  $node->field_job_offer_description['und'][0]['value'] = $values['job_offer_description']['value'];
  $node->field_job_offer_description['und'][0]['format'] = $values['job_offer_description']['format'];
  $node->field_job_offer_requirements['und'][0]['value'] = $values['job_offer_requirements']['value'];
  $node->field_job_offer_requirements['und'][0]['format'] = $values['job_offer_requirements']['format'];
  $node->field_job_offer_conditions['und'][0]['value'] = $values['job_offer_conditions']['value'];
  $node->field_job_offer_conditions['und'][0]['format'] = $values['job_offer_conditions']['format'];
  node_save($node);
  // Show a message to the user
  if ($status) {
    drupal_set_message('La teva oferta de feina ha estat publicada correctament.', 'status');
  }
  else {
    drupal_set_message('La teva oferta de feina ha estat desada correctament i està pendent d\'aprovació per part dels administradors de Xarxanet.', 'status');
  }
  // Redirect the user to the View
  $form_state['redirect'] = '/ofertes-feina';
}

/**
 * Helper function to determine if current user has role/roles
 *
 * @see     https://tinyurl.com/yfeqhaoa
 *
 * @param   array  $roles
 *          An array of roles to compare against.
 *
 * @return  boolean
 */
function user_has_roles($roles) {
  return !!count(array_intersect(is_array($roles) ? $roles : array($roles), array_values($GLOBALS['user']->roles)));
}
