<?php

/**
 * Helper to implementation of hook_content_default_fields().
 */
function _rss_portals_xarxanet_content_default_fields() {
	$fields = array ();
	
	// Exported field: field_imatge_feed
	$fields [] = array (
			'field_name' => 'field_imatge_feed',
			'type_name' => 'feed_ambiental',
			'display_settings' => array (
					'label' => array (
							'format' => 'above',
							'exclude' => 0 
					),
					'teaser' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'full' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'4' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'2' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'3' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'token' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					) 
			),
			'widget_active' => '1',
			'type' => 'filefield',
			'required' => '0',
			'multiple' => '0',
			'module' => 'filefield',
			'active' => '1',
			'list_field' => '0',
			'list_default' => 1,
			'description_field' => '0',
			'widget' => array (
					'file_extensions' => 'png gif jpg jpeg',
					'file_path' => '',
					'progress_indicator' => 'bar',
					'max_filesize_per_file' => '',
					'max_filesize_per_node' => '',
					'max_resolution' => '100x100',
					'min_resolution' => '22x22',
					'alt' => '',
					'custom_alt' => 0,
					'title' => '',
					'custom_title' => 0,
					'title_type' => 'textfield',
					'default_image' => NULL,
					'use_default_image' => 0,
					'label' => 'Imatge de Feed',
					'weight' => '-4',
					'description' => '',
					'type' => 'imagefield_widget',
					'module' => 'imagefield' 
			) 
	);
	
	// Exported field: field_imatge_feed
	$fields [] = array (
			'field_name' => 'field_imatge_feed',
			'type_name' => 'feed_comunitari',
			'display_settings' => array (
					'label' => array (
							'format' => 'above',
							'exclude' => 0 
					),
					'teaser' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'full' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'4' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'2' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'3' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'token' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					) 
			),
			'widget_active' => '1',
			'type' => 'filefield',
			'required' => '0',
			'multiple' => '0',
			'module' => 'filefield',
			'active' => '1',
			'list_field' => '0',
			'list_default' => 1,
			'description_field' => '0',
			'widget' => array (
					'file_extensions' => 'png gif jpg jpeg',
					'file_path' => '',
					'progress_indicator' => 'bar',
					'max_filesize_per_file' => '',
					'max_filesize_per_node' => '',
					'max_resolution' => '100x100',
					'min_resolution' => '22x22',
					'alt' => '',
					'custom_alt' => 0,
					'title' => '',
					'custom_title' => 0,
					'title_type' => 'textfield',
					'default_image' => NULL,
					'use_default_image' => 0,
					'label' => 'Imatge de Feed',
					'weight' => '-4',
					'description' => '',
					'type' => 'imagefield_widget',
					'module' => 'imagefield' 
			) 
	);
	
	// Exported field: field_imatge_feed
	$fields [] = array (
			'field_name' => 'field_imatge_feed',
			'type_name' => 'feed_cultural',
			'display_settings' => array (
					'label' => array (
							'format' => 'above',
							'exclude' => 0 
					),
					'teaser' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'full' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'4' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'2' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'3' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'token' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					) 
			),
			'widget_active' => '1',
			'type' => 'filefield',
			'required' => '0',
			'multiple' => '0',
			'module' => 'filefield',
			'active' => '1',
			'list_field' => '0',
			'list_default' => 1,
			'description_field' => '0',
			'widget' => array (
					'file_extensions' => 'png gif jpg jpeg',
					'file_path' => '',
					'progress_indicator' => 'bar',
					'max_filesize_per_file' => '',
					'max_filesize_per_node' => '',
					'max_resolution' => '100x100',
					'min_resolution' => '22x22',
					'alt' => '',
					'custom_alt' => 0,
					'title' => '',
					'custom_title' => 0,
					'title_type' => 'textfield',
					'default_image' => NULL,
					'use_default_image' => 0,
					'label' => 'Imatge de Feed',
					'weight' => '-4',
					'description' => '',
					'type' => 'imagefield_widget',
					'module' => 'imagefield' 
			) 
	);
	
	// Exported field: field_imatge_feed
	$fields [] = array (
			'field_name' => 'field_imatge_feed',
			'type_name' => 'feed_economic',
			'display_settings' => array (
					'label' => array (
							'format' => 'above',
							'exclude' => 0 
					),
					'teaser' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'full' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'4' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'2' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'3' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'token' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					) 
			),
			'widget_active' => '1',
			'type' => 'filefield',
			'required' => '0',
			'multiple' => '0',
			'module' => 'filefield',
			'active' => '1',
			'list_field' => '0',
			'list_default' => 1,
			'description_field' => '0',
			'widget' => array (
					'file_extensions' => 'png gif jpg jpeg',
					'file_path' => '',
					'progress_indicator' => 'bar',
					'max_filesize_per_file' => '',
					'max_filesize_per_node' => '',
					'max_resolution' => '100x100',
					'min_resolution' => '22x22',
					'alt' => '',
					'custom_alt' => 0,
					'title' => '',
					'custom_title' => 0,
					'title_type' => 'textfield',
					'default_image' => NULL,
					'use_default_image' => 0,
					'label' => 'Imatge de Feed',
					'weight' => '-4',
					'description' => '',
					'type' => 'imagefield_widget',
					'module' => 'imagefield' 
			) 
	);
	
	// Exported field: field_imatge_feed
	$fields [] = array (
			'field_name' => 'field_imatge_feed',
			'type_name' => 'feed_formacio',
			'display_settings' => array (
					'label' => array (
							'format' => 'above',
							'exclude' => 0 
					),
					'teaser' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'full' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'4' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'2' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'3' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'token' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					) 
			),
			'widget_active' => '1',
			'type' => 'filefield',
			'required' => '0',
			'multiple' => '0',
			'module' => 'filefield',
			'active' => '1',
			'list_field' => '0',
			'list_default' => 1,
			'description_field' => '0',
			'widget' => array (
					'file_extensions' => 'png gif jpg jpeg',
					'file_path' => '',
					'progress_indicator' => 'bar',
					'max_filesize_per_file' => '',
					'max_filesize_per_node' => '',
					'max_resolution' => '100x100',
					'min_resolution' => '22x22',
					'alt' => '',
					'custom_alt' => 0,
					'title' => '',
					'custom_title' => 0,
					'title_type' => 'textfield',
					'default_image' => NULL,
					'use_default_image' => 0,
					'label' => 'Imatge de Feed',
					'weight' => '-4',
					'description' => '',
					'type' => 'imagefield_widget',
					'module' => 'imagefield' 
			) 
	);
	
	// Exported field: field_imatge_feed
	$fields [] = array (
			'field_name' => 'field_imatge_feed',
			'type_name' => 'feed_informatic',
			'display_settings' => array (
					'label' => array (
							'format' => 'above',
							'exclude' => 0 
					),
					'teaser' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'full' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'4' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'2' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'3' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'token' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					) 
			),
			'widget_active' => '1',
			'type' => 'filefield',
			'required' => '0',
			'multiple' => '0',
			'module' => 'filefield',
			'active' => '1',
			'list_field' => '0',
			'list_default' => 1,
			'description_field' => '0',
			'widget' => array (
					'file_extensions' => 'png gif jpg jpeg',
					'file_path' => '',
					'progress_indicator' => 'bar',
					'max_filesize_per_file' => '',
					'max_filesize_per_node' => '',
					'max_resolution' => '100x100',
					'min_resolution' => '22x22',
					'alt' => '',
					'custom_alt' => 0,
					'title' => '',
					'custom_title' => 0,
					'title_type' => 'textfield',
					'default_image' => NULL,
					'use_default_image' => 0,
					'label' => 'Imatge de Feed',
					'weight' => '-4',
					'description' => '',
					'type' => 'imagefield_widget',
					'module' => 'imagefield' 
			) 
	);
	
	// Exported field: field_imatge_feed
	$fields [] = array (
			'field_name' => 'field_imatge_feed',
			'type_name' => 'feed_internacional',
			'display_settings' => array (
					'label' => array (
							'format' => 'above',
							'exclude' => 0 
					),
					'teaser' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'full' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'4' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'2' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'3' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'token' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					) 
			),
			'widget_active' => '1',
			'type' => 'filefield',
			'required' => '0',
			'multiple' => '0',
			'module' => 'filefield',
			'active' => '1',
			'list_field' => '0',
			'list_default' => 1,
			'description_field' => '0',
			'widget' => array (
					'file_extensions' => 'png gif jpg jpeg',
					'file_path' => '',
					'progress_indicator' => 'bar',
					'max_filesize_per_file' => '',
					'max_filesize_per_node' => '',
					'max_resolution' => '100x100',
					'min_resolution' => '22x22',
					'alt' => '',
					'custom_alt' => 0,
					'title' => '',
					'custom_title' => 0,
					'title_type' => 'textfield',
					'default_image' => NULL,
					'use_default_image' => 0,
					'label' => 'Imatge de Feed',
					'weight' => '-4',
					'description' => '',
					'type' => 'imagefield_widget',
					'module' => 'imagefield' 
			) 
	);
	
	// Exported field: field_imatge_feed
	$fields [] = array (
			'field_name' => 'field_imatge_feed',
			'type_name' => 'feed_juridic',
			'display_settings' => array (
					'label' => array (
							'format' => 'above',
							'exclude' => 0 
					),
					'teaser' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'full' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'4' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'2' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'3' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'token' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					) 
			),
			'widget_active' => '1',
			'type' => 'filefield',
			'required' => '0',
			'multiple' => '0',
			'module' => 'filefield',
			'active' => '1',
			'list_field' => '0',
			'list_default' => 1,
			'description_field' => '0',
			'widget' => array (
					'file_extensions' => 'png gif jpg jpeg',
					'file_path' => '',
					'progress_indicator' => 'bar',
					'max_filesize_per_file' => '',
					'max_filesize_per_node' => '',
					'max_resolution' => '100x100',
					'min_resolution' => '22x22',
					'alt' => '',
					'custom_alt' => 0,
					'title' => '',
					'custom_title' => 0,
					'title_type' => 'textfield',
					'default_image' => NULL,
					'use_default_image' => 0,
					'label' => 'Imatge de Feed',
					'weight' => '-4',
					'description' => '',
					'type' => 'imagefield_widget',
					'module' => 'imagefield' 
			) 
	);
	
	// Exported field: field_imatge_feed
	$fields [] = array (
			'field_name' => 'field_imatge_feed',
			'type_name' => 'feed_portada',
			'display_settings' => array (
					'label' => array (
							'format' => 'above',
							'exclude' => 0 
					),
					'teaser' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'full' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'4' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'2' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'3' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'token' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					) 
			),
			'widget_active' => '1',
			'type' => 'filefield',
			'required' => '0',
			'multiple' => '0',
			'module' => 'filefield',
			'active' => '1',
			'list_field' => '0',
			'list_default' => 1,
			'description_field' => '0',
			'widget' => array (
					'file_extensions' => 'png gif jpg jpeg',
					'file_path' => '',
					'progress_indicator' => 'bar',
					'max_filesize_per_file' => '',
					'max_filesize_per_node' => '',
					'max_resolution' => '100x100',
					'min_resolution' => '22x22',
					'alt' => '',
					'custom_alt' => 0,
					'title' => '',
					'custom_title' => 0,
					'title_type' => 'textfield',
					'default_image' => NULL,
					'use_default_image' => 0,
					'label' => 'Imatge de Feed',
					'weight' => '-4',
					'description' => '',
					'type' => 'imagefield_widget',
					'module' => 'imagefield' 
			) 
	);
	
	// Exported field: field_imatge_feed
	$fields [] = array (
			'field_name' => 'field_imatge_feed',
			'type_name' => 'feed_projectes',
			'display_settings' => array (
					'label' => array (
							'format' => 'above',
							'exclude' => 0 
					),
					'teaser' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'full' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'4' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'2' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'3' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'token' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					) 
			),
			'widget_active' => '1',
			'type' => 'filefield',
			'required' => '0',
			'multiple' => '0',
			'module' => 'filefield',
			'active' => '1',
			'list_field' => '0',
			'list_default' => 1,
			'description_field' => '0',
			'widget' => array (
					'file_extensions' => 'png gif jpg jpeg',
					'file_path' => '',
					'progress_indicator' => 'bar',
					'max_filesize_per_file' => '',
					'max_filesize_per_node' => '',
					'max_resolution' => '100x100',
					'min_resolution' => '22x22',
					'alt' => '',
					'custom_alt' => 0,
					'title' => '',
					'custom_title' => 0,
					'title_type' => 'textfield',
					'default_image' => NULL,
					'use_default_image' => 0,
					'label' => 'Imatge de Feed',
					'weight' => '-4',
					'description' => '',
					'type' => 'imagefield_widget',
					'module' => 'imagefield' 
			) 
	);
	
	// Exported field: field_imatge_feed
	$fields [] = array (
			'field_name' => 'field_imatge_feed',
			'type_name' => 'feed_social',
			'display_settings' => array (
					'label' => array (
							'format' => 'above',
							'exclude' => 0 
					),
					'teaser' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'full' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'4' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'2' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'3' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'token' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					) 
			),
			'widget_active' => '1',
			'type' => 'filefield',
			'required' => '0',
			'multiple' => '0',
			'module' => 'filefield',
			'active' => '1',
			'list_field' => '0',
			'list_default' => 1,
			'description_field' => '0',
			'widget' => array (
					'file_extensions' => 'png gif jpg jpeg',
					'file_path' => '',
					'progress_indicator' => 'bar',
					'max_filesize_per_file' => '',
					'max_filesize_per_node' => '',
					'max_resolution' => '100x100',
					'min_resolution' => '22x22',
					'alt' => '',
					'custom_alt' => 0,
					'title' => '',
					'custom_title' => 0,
					'title_type' => 'textfield',
					'default_image' => NULL,
					'use_default_image' => 0,
					'label' => 'Imatge de Feed',
					'weight' => '-4',
					'description' => '',
					'type' => 'imagefield_widget',
					'module' => 'imagefield' 
			) 
	);
	
	// Exported field: field_imatge_feed
	$fields [] = array (
			'field_name' => 'field_imatge_feed',
			'type_name' => 'node_feeder',
			'display_settings' => array (
					'label' => array (
							'format' => 'above',
							'exclude' => 0 
					),
					'teaser' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'full' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'4' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'2' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'3' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'token' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					) 
			),
			'widget_active' => '1',
			'type' => 'filefield',
			'required' => '0',
			'multiple' => '0',
			'module' => 'filefield',
			'active' => '1',
			'list_field' => '0',
			'list_default' => 1,
			'description_field' => '0',
			'widget' => array (
					'file_extensions' => 'png gif jpg jpeg',
					'file_path' => '',
					'progress_indicator' => 'bar',
					'max_filesize_per_file' => '',
					'max_filesize_per_node' => '',
					'max_resolution' => '85x85',
					'min_resolution' => '85x85',
					'alt' => '',
					'custom_alt' => 0,
					'title' => '',
					'custom_title' => 0,
					'title_type' => 'textfield',
					'default_image' => NULL,
					'use_default_image' => 0,
					'label' => 'Imatge de Feed',
					'weight' => '-4',
					'description' => '',
					'type' => 'imagefield_widget',
					'module' => 'imagefield' 
			) 
	);
	
	// Exported field: field_imatge_feed
	$fields [] = array (
			'field_name' => 'field_imatge_feed',
			'type_name' => 'portada_node_feeder',
			'display_settings' => array (
					'label' => array (
							'format' => 'above',
							'exclude' => 0 
					),
					'teaser' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'full' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'4' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'2' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'3' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					),
					'token' => array (
							'format' => 'image_plain',
							'exclude' => 0 
					) 
			),
			'widget_active' => '1',
			'type' => 'filefield',
			'required' => '0',
			'multiple' => '0',
			'module' => 'filefield',
			'active' => '1',
			'list_field' => '0',
			'list_default' => 1,
			'description_field' => '0',
			'widget' => array (
					'file_extensions' => 'png gif jpg jpeg',
					'file_path' => '',
					'progress_indicator' => 'bar',
					'max_filesize_per_file' => '',
					'max_filesize_per_node' => '',
					'max_resolution' => '85x85',
					'min_resolution' => '85x85',
					'alt' => '',
					'custom_alt' => 0,
					'title' => '',
					'custom_title' => 0,
					'title_type' => 'textfield',
					'default_image' => NULL,
					'use_default_image' => 0,
					'label' => 'Imatge de Feed',
					'weight' => '-4',
					'description' => '',
					'type' => 'imagefield_widget',
					'module' => 'imagefield' 
			) 
	);
	
	// Translatables
	array (
			t ( 'Imatge de Feed' ) 
	);
	
	return $fields;
}

/**
 * Helper to implementation of hook_ctools_plugin_api().
 */
function _rss_portals_xarxanet_ctools_plugin_api() {
	$args = func_get_args ();
	$module = array_shift ( $args );
	$api = array_shift ( $args );
	if ($module == "feeds" && $api == "feeds_importer_default") {
		return array (
				"version" => 1 
		);
	}
}

/**
 * Helper to implementation of hook_feeds_importer_default().
 */
function _rss_portals_xarxanet_feeds_importer_default() {
	$export = array ();
	$feeds_importer = new stdClass ();
	$feeds_importer->disabled = FALSE; /* Edit this to true to make a default feeds_importer disabled initially */
	$feeds_importer->api_version = 1;
	$feeds_importer->id = 'feed_ambiental';
	$feeds_importer->config = array (
			'name' => 'Feed Ambiental',
			'description' => '',
			'fetcher' => array (
					'plugin_key' => 'FeedsHTTPFetcher',
					'config' => array (
							'auto_detect_feeds' => FALSE,
							'use_pubsubhubbub' => FALSE,
							'designated_hub' => '' 
					) 
			),
			'parser' => array (
					'plugin_key' => 'FeedsSyndicationParser',
					'config' => array () 
			),
			'processor' => array (
					'plugin_key' => 'FeedsNodeProcessor',
					'config' => array (
							'content_type' => 'node_feeder',
							'input_format' => '1',
							'update_existing' => '1',
							'expire' => '604800',
							'mappings' => array (
									0 => array (
											'source' => 'title',
											'target' => 'title',
											'unique' => FALSE 
									),
									1 => array (
											'source' => 'description',
											'target' => 'body',
											'unique' => FALSE 
									),
									2 => array (
											'source' => 'timestamp',
											'target' => 'created',
											'unique' => FALSE 
									),
									3 => array (
											'source' => 'guid',
											'target' => 'guid',
											'unique' => FALSE 
									),
									4 => array (
											'source' => 'url',
											'target' => 'url',
											'unique' => FALSE 
									) 
							),
							'author' => '6850' 
					) 
			),
			'content_type' => 'feed_ambiental',
			'update' => 0,
			'import_period' => '3600',
			'expire_period' => 3600,
			'import_on_create' => 1 
	);
	
	$export ['feed_ambiental'] = $feeds_importer;
	$feeds_importer = new stdClass ();
	$feeds_importer->disabled = FALSE; /* Edit this to true to make a default feeds_importer disabled initially */
	$feeds_importer->api_version = 1;
	$feeds_importer->id = 'feed_comunitari';
	$feeds_importer->config = array (
			'name' => 'Feed Comunitari',
			'description' => '',
			'fetcher' => array (
					'plugin_key' => 'FeedsHTTPFetcher',
					'config' => array (
							'auto_detect_feeds' => FALSE,
							'use_pubsubhubbub' => FALSE,
							'designated_hub' => '' 
					) 
			),
			'parser' => array (
					'plugin_key' => 'FeedsSyndicationParser',
					'config' => array () 
			),
			'processor' => array (
					'plugin_key' => 'FeedsNodeProcessor',
					'config' => array (
							'content_type' => 'node_feeder',
							'input_format' => '1',
							'update_existing' => '1',
							'expire' => '604800',
							'mappings' => array (
									0 => array (
											'source' => 'title',
											'target' => 'title',
											'unique' => FALSE 
									),
									1 => array (
											'source' => 'description',
											'target' => 'body',
											'unique' => FALSE 
									),
									2 => array (
											'source' => 'timestamp',
											'target' => 'created',
											'unique' => FALSE 
									),
									3 => array (
											'source' => 'guid',
											'target' => 'guid',
											'unique' => FALSE 
									),
									4 => array (
											'source' => 'url',
											'target' => 'url',
											'unique' => FALSE 
									) 
							),
							'author' => '6851' 
					) 
			),
			'content_type' => 'feed_comunitari',
			'update' => 0,
			'import_period' => '3600',
			'expire_period' => 3600,
			'import_on_create' => 1 
	);
	
	$export ['feed_comunitari'] = $feeds_importer;
	$feeds_importer = new stdClass ();
	$feeds_importer->disabled = FALSE; /* Edit this to true to make a default feeds_importer disabled initially */
	$feeds_importer->api_version = 1;
	$feeds_importer->id = 'feed_cultural';
	$feeds_importer->config = array (
			'name' => 'Feed Cultural',
			'description' => '',
			'fetcher' => array (
					'plugin_key' => 'FeedsHTTPFetcher',
					'config' => array (
							'auto_detect_feeds' => FALSE,
							'use_pubsubhubbub' => FALSE,
							'designated_hub' => '' 
					) 
			),
			'parser' => array (
					'plugin_key' => 'FeedsSyndicationParser',
					'config' => array () 
			),
			'processor' => array (
					'plugin_key' => 'FeedsNodeProcessor',
					'config' => array (
							'content_type' => 'node_feeder',
							'input_format' => '1',
							'update_existing' => '1',
							'expire' => '604800',
							'mappings' => array (
									0 => array (
											'source' => 'title',
											'target' => 'title',
											'unique' => FALSE 
									),
									1 => array (
											'source' => 'description',
											'target' => 'body',
											'unique' => FALSE 
									),
									2 => array (
											'source' => 'timestamp',
											'target' => 'created',
											'unique' => FALSE 
									),
									3 => array (
											'source' => 'guid',
											'target' => 'guid',
											'unique' => FALSE 
									),
									4 => array (
											'source' => 'url',
											'target' => 'url',
											'unique' => FALSE 
									) 
							),
							'author' => '6852' 
					) 
			),
			'content_type' => 'feed_cultural',
			'update' => 0,
			'import_period' => '3600',
			'expire_period' => 3600,
			'import_on_create' => 1 
	);
	
	$export ['feed_cultural'] = $feeds_importer;
	$feeds_importer = new stdClass ();
	$feeds_importer->disabled = FALSE; /* Edit this to true to make a default feeds_importer disabled initially */
	$feeds_importer->api_version = 1;
	$feeds_importer->id = 'feed_de_portada';
	$feeds_importer->config = array (
			'name' => 'Feed de Portada',
			'description' => 'Feed per a la portada de xarxanet.org',
			'fetcher' => array (
					'plugin_key' => 'FeedsHTTPFetcher',
					'config' => array (
							'auto_detect_feeds' => FALSE,
							'use_pubsubhubbub' => FALSE,
							'designated_hub' => '' 
					) 
			),
			'parser' => array (
					'plugin_key' => 'FeedsSyndicationParser',
					'config' => array () 
			),
			'processor' => array (
					'plugin_key' => 'FeedsNodeProcessor',
					'config' => array (
							'content_type' => 'portada_node_feeder',
							'input_format' => '1',
							'update_existing' => '1',
							'expire' => '-1',
							'mappings' => array (
									0 => array (
											'source' => 'title',
											'target' => 'title',
											'unique' => FALSE 
									),
									1 => array (
											'source' => 'description',
											'target' => 'body',
											'unique' => FALSE 
									),
									2 => array (
											'source' => 'url',
											'target' => 'url',
											'unique' => 1 
									),
									3 => array (
											'source' => 'timestamp',
											'target' => 'created',
											'unique' => FALSE 
									),
									4 => array (
											'source' => 'guid',
											'target' => 'guid',
											'unique' => 1 
									) 
							),
							'author' => '6860' 
					) 
			),
			'content_type' => 'feed_portada',
			'update' => 0,
			'import_period' => '0',
			'expire_period' => 3600,
			'import_on_create' => 1 
	);
	
	$export ['feed_de_portada'] = $feeds_importer;
	$feeds_importer = new stdClass ();
	$feeds_importer->disabled = FALSE; /* Edit this to true to make a default feeds_importer disabled initially */
	$feeds_importer->api_version = 1;
	$feeds_importer->id = 'feed_econ_mic';
	$feeds_importer->config = array (
			'name' => 'Feed Econòmic',
			'description' => '',
			'fetcher' => array (
					'plugin_key' => 'FeedsHTTPFetcher',
					'config' => array (
							'auto_detect_feeds' => FALSE,
							'use_pubsubhubbub' => FALSE,
							'designated_hub' => '' 
					) 
			),
			'parser' => array (
					'plugin_key' => 'FeedsSyndicationParser',
					'config' => array () 
			),
			'processor' => array (
					'plugin_key' => 'FeedsNodeProcessor',
					'config' => array (
							'content_type' => 'node_feeder',
							'input_format' => '1',
							'update_existing' => '1',
							'expire' => '604800',
							'mappings' => array (
									0 => array (
											'source' => 'title',
											'target' => 'title',
											'unique' => FALSE 
									),
									1 => array (
											'source' => 'description',
											'target' => 'body',
											'unique' => FALSE 
									),
									2 => array (
											'source' => 'timestamp',
											'target' => 'created',
											'unique' => FALSE 
									),
									3 => array (
											'source' => 'guid',
											'target' => 'guid',
											'unique' => FALSE 
									),
									4 => array (
											'source' => 'url',
											'target' => 'url',
											'unique' => FALSE 
									) 
							),
							'author' => '6855' 
					) 
			),
			'content_type' => 'feed_economic',
			'update' => 0,
			'import_period' => '3600',
			'expire_period' => 3600,
			'import_on_create' => 1 
	);
	
	$export ['feed_econ_mic'] = $feeds_importer;
	$feeds_importer = new stdClass ();
	$feeds_importer->disabled = FALSE; /* Edit this to true to make a default feeds_importer disabled initially */
	$feeds_importer->api_version = 1;
	$feeds_importer->id = 'feed_formacio';
	$feeds_importer->config = array (
			'name' => 'Feed Formacio',
			'description' => '',
			'fetcher' => array (
					'plugin_key' => 'FeedsHTTPFetcher',
					'config' => array (
							'auto_detect_feeds' => FALSE,
							'use_pubsubhubbub' => FALSE,
							'designated_hub' => '' 
					) 
			),
			'parser' => array (
					'plugin_key' => 'FeedsSyndicationParser',
					'config' => array () 
			),
			'processor' => array (
					'plugin_key' => 'FeedsNodeProcessor',
					'config' => array (
							'content_type' => 'node_feeder',
							'input_format' => '1',
							'update_existing' => '1',
							'expire' => '604800',
							'mappings' => array (
									0 => array (
											'source' => 'title',
											'target' => 'title',
											'unique' => FALSE 
									),
									1 => array (
											'source' => 'description',
											'target' => 'body',
											'unique' => FALSE 
									),
									2 => array (
											'source' => 'timestamp',
											'target' => 'created',
											'unique' => FALSE 
									),
									3 => array (
											'source' => 'guid',
											'target' => 'guid',
											'unique' => FALSE 
									),
									4 => array (
											'source' => 'url',
											'target' => 'url',
											'unique' => FALSE 
									) 
							),
							'author' => '6856' 
					) 
			),
			'content_type' => 'feed_formacio',
			'update' => 0,
			'import_period' => '3600',
			'expire_period' => 3600,
			'import_on_create' => 1 
	);
	
	$export ['feed_formacio'] = $feeds_importer;
	$feeds_importer = new stdClass ();
	$feeds_importer->disabled = FALSE; /* Edit this to true to make a default feeds_importer disabled initially */
	$feeds_importer->api_version = 1;
	$feeds_importer->id = 'feed_informatic';
	$feeds_importer->config = array (
			'name' => 'Feed Informatic',
			'description' => '',
			'fetcher' => array (
					'plugin_key' => 'FeedsHTTPFetcher',
					'config' => array (
							'auto_detect_feeds' => FALSE,
							'use_pubsubhubbub' => FALSE,
							'designated_hub' => '' 
					) 
			),
			'parser' => array (
					'plugin_key' => 'FeedsSyndicationParser',
					'config' => array () 
			),
			'processor' => array (
					'plugin_key' => 'FeedsNodeProcessor',
					'config' => array (
							'content_type' => 'node_feeder',
							'input_format' => '1',
							'update_existing' => '1',
							'expire' => '604800',
							'mappings' => array (
									0 => array (
											'source' => 'title',
											'target' => 'title',
											'unique' => FALSE 
									),
									1 => array (
											'source' => 'description',
											'target' => 'body',
											'unique' => FALSE 
									),
									2 => array (
											'source' => 'timestamp',
											'target' => 'created',
											'unique' => FALSE 
									),
									3 => array (
											'source' => 'guid',
											'target' => 'guid',
											'unique' => FALSE 
									),
									4 => array (
											'source' => 'url',
											'target' => 'url',
											'unique' => FALSE 
									) 
							),
							'author' => '6857' 
					) 
			),
			'content_type' => 'feed_informatic',
			'update' => 0,
			'import_period' => '3600',
			'expire_period' => 3600,
			'import_on_create' => 1 
	);
	
	$export ['feed_informatic'] = $feeds_importer;
	$feeds_importer = new stdClass ();
	$feeds_importer->disabled = FALSE; /* Edit this to true to make a default feeds_importer disabled initially */
	$feeds_importer->api_version = 1;
	$feeds_importer->id = 'feed_internacional';
	$feeds_importer->config = array (
			'name' => 'Feed Internacional',
			'description' => '',
			'fetcher' => array (
					'plugin_key' => 'FeedsHTTPFetcher',
					'config' => array (
							'auto_detect_feeds' => FALSE,
							'use_pubsubhubbub' => FALSE,
							'designated_hub' => '' 
					) 
			),
			'parser' => array (
					'plugin_key' => 'FeedsSyndicationParser',
					'config' => array () 
			),
			'processor' => array (
					'plugin_key' => 'FeedsNodeProcessor',
					'config' => array (
							'content_type' => 'node_feeder',
							'input_format' => '1',
							'update_existing' => '1',
							'expire' => '604800',
							'mappings' => array (
									0 => array (
											'source' => 'title',
											'target' => 'title',
											'unique' => FALSE 
									),
									1 => array (
											'source' => 'description',
											'target' => 'body',
											'unique' => FALSE 
									),
									2 => array (
											'source' => 'timestamp',
											'target' => 'created',
											'unique' => FALSE 
									),
									3 => array (
											'source' => 'guid',
											'target' => 'guid',
											'unique' => FALSE 
									),
									4 => array (
											'source' => 'url',
											'target' => 'url',
											'unique' => FALSE 
									) 
							),
							'author' => '6853' 
					) 
			),
			'content_type' => 'feed_internacional',
			'update' => 0,
			'import_period' => '3600',
			'expire_period' => 3600,
			'import_on_create' => 1 
	);
	
	$export ['feed_internacional'] = $feeds_importer;
	$feeds_importer = new stdClass ();
	$feeds_importer->disabled = FALSE; /* Edit this to true to make a default feeds_importer disabled initially */
	$feeds_importer->api_version = 1;
	$feeds_importer->id = 'feed_juridic';
	$feeds_importer->config = array (
			'name' => 'Feed Juridic',
			'description' => '',
			'fetcher' => array (
					'plugin_key' => 'FeedsHTTPFetcher',
					'config' => array (
							'auto_detect_feeds' => FALSE,
							'use_pubsubhubbub' => FALSE,
							'designated_hub' => '' 
					) 
			),
			'parser' => array (
					'plugin_key' => 'FeedsSyndicationParser',
					'config' => array () 
			),
			'processor' => array (
					'plugin_key' => 'FeedsNodeProcessor',
					'config' => array (
							'content_type' => 'node_feeder',
							'input_format' => '1',
							'update_existing' => '1',
							'expire' => '604800',
							'mappings' => array (
									0 => array (
											'source' => 'title',
											'target' => 'title',
											'unique' => FALSE 
									),
									1 => array (
											'source' => 'description',
											'target' => 'body',
											'unique' => FALSE 
									),
									2 => array (
											'source' => 'timestamp',
											'target' => 'created',
											'unique' => FALSE 
									),
									3 => array (
											'source' => 'guid',
											'target' => 'guid',
											'unique' => FALSE 
									),
									4 => array (
											'source' => 'url',
											'target' => 'url',
											'unique' => FALSE 
									) 
							),
							'author' => '6858' 
					) 
			),
			'content_type' => 'feed_juridic',
			'update' => 0,
			'import_period' => '3600',
			'expire_period' => 3600,
			'import_on_create' => 1 
	);
	
	$export ['feed_juridic'] = $feeds_importer;
	$feeds_importer = new stdClass ();
	$feeds_importer->disabled = FALSE; /* Edit this to true to make a default feeds_importer disabled initially */
	$feeds_importer->api_version = 1;
	$feeds_importer->id = 'feed_projectes';
	$feeds_importer->config = array (
			'name' => 'Feed Projectes',
			'description' => '',
			'fetcher' => array (
					'plugin_key' => 'FeedsHTTPFetcher',
					'config' => array (
							'auto_detect_feeds' => FALSE,
							'use_pubsubhubbub' => FALSE,
							'designated_hub' => '' 
					) 
			),
			'parser' => array (
					'plugin_key' => 'FeedsSyndicationParser',
					'config' => array () 
			),
			'processor' => array (
					'plugin_key' => 'FeedsNodeProcessor',
					'config' => array (
							'content_type' => 'node_feeder',
							'input_format' => '1',
							'update_existing' => '1',
							'expire' => '604800',
							'mappings' => array (
									0 => array (
											'source' => 'title',
											'target' => 'title',
											'unique' => FALSE 
									),
									1 => array (
											'source' => 'description',
											'target' => 'body',
											'unique' => FALSE 
									),
									2 => array (
											'source' => 'timestamp',
											'target' => 'created',
											'unique' => FALSE 
									),
									3 => array (
											'source' => 'guid',
											'target' => 'guid',
											'unique' => FALSE 
									),
									4 => array (
											'source' => 'url',
											'target' => 'url',
											'unique' => FALSE 
									) 
							),
							'author' => '6859' 
					) 
			),
			'content_type' => 'feed_projectes',
			'update' => 0,
			'import_period' => '3600',
			'expire_period' => 3600,
			'import_on_create' => 1 
	);
	
	$export ['feed_projectes'] = $feeds_importer;
	$feeds_importer = new stdClass ();
	$feeds_importer->disabled = FALSE; /* Edit this to true to make a default feeds_importer disabled initially */
	$feeds_importer->api_version = 1;
	$feeds_importer->id = 'feed_social';
	$feeds_importer->config = array (
			'name' => 'Feed Social',
			'description' => '',
			'fetcher' => array (
					'plugin_key' => 'FeedsHTTPFetcher',
					'config' => array (
							'auto_detect_feeds' => FALSE,
							'use_pubsubhubbub' => FALSE,
							'designated_hub' => '' 
					) 
			),
			'parser' => array (
					'plugin_key' => 'FeedsSyndicationParser',
					'config' => array () 
			),
			'processor' => array (
					'plugin_key' => 'FeedsNodeProcessor',
					'config' => array (
							'content_type' => 'node_feeder',
							'input_format' => '1',
							'update_existing' => '1',
							'expire' => '604800',
							'mappings' => array (
									0 => array (
											'source' => 'title',
											'target' => 'title',
											'unique' => FALSE 
									),
									1 => array (
											'source' => 'description',
											'target' => 'body',
											'unique' => FALSE 
									),
									2 => array (
											'source' => 'timestamp',
											'target' => 'created',
											'unique' => FALSE 
									),
									3 => array (
											'source' => 'guid',
											'target' => 'guid',
											'unique' => FALSE 
									),
									4 => array (
											'source' => 'url',
											'target' => 'url',
											'unique' => FALSE 
									) 
							),
							'author' => '6854' 
					) 
			),
			'content_type' => 'feed_social',
			'update' => 0,
			'import_period' => '3600',
			'expire_period' => 3600,
			'import_on_create' => 1 
	);
	
	$export ['feed_social'] = $feeds_importer;
	return $export;
}

/**
 * Helper to implementation of hook_imagecache_default_presets().
 */
function _rss_portals_xarxanet_imagecache_default_presets() {
	$items = array (
			'imatge_feed_item' => array (
					'presetname' => 'imatge_feed_item',
					'actions' => array (
							'0' => array (
									'weight' => '0',
									'module' => 'imagecache',
									'action' => 'imagecache_resize',
									'data' => array (
											'width' => '22',
											'height' => '22' 
									) 
							) 
					) 
			) 
	);
	return $items;
}

/**
 * Helper to implementation of hook_user_default_permissions().
 */
function _rss_portals_xarxanet_user_default_permissions() {
	$permissions = array ();
	
	// Exported permission: clear feed_ambiental feeds
	$permissions [] = array (
			'name' => 'clear feed_ambiental feeds',
			'roles' => array (
					'0' => 'Entitat promotora ambiental' 
			) 
	);
	
	// Exported permission: clear feed_comunitari feeds
	$permissions [] = array (
			'name' => 'clear feed_comunitari feeds',
			'roles' => array (
					'0' => 'Entitat promotora comunitari' 
			) 
	);
	
	// Exported permission: clear feed_cultural feeds
	$permissions [] = array (
			'name' => 'clear feed_cultural feeds',
			'roles' => array (
					'0' => 'Entitat promotora cultural' 
			) 
	);
	
	// Exported permission: clear feed_de_portada feeds
	$permissions [] = array (
			'name' => 'clear feed_de_portada feeds',
			'roles' => array (
					'0' => 'Entitat administradora' 
			) 
	);
	
	// Exported permission: clear feed_econ_mic feeds
	$permissions [] = array (
			'name' => 'clear feed_econ_mic feeds',
			'roles' => array (
					'0' => 'Entitat promotora economic' 
			) 
	);
	
	// Exported permission: clear feed_formacio feeds
	$permissions [] = array (
			'name' => 'clear feed_formacio feeds',
			'roles' => array (
					'0' => 'Entitat promotora formacio' 
			) 
	);
	
	// Exported permission: clear feed_informatic feeds
	$permissions [] = array (
			'name' => 'clear feed_informatic feeds',
			'roles' => array (
					'0' => 'Entitat promotora informatic' 
			) 
	);
	
	// Exported permission: clear feed_internacional feeds
	$permissions [] = array (
			'name' => 'clear feed_internacional feeds',
			'roles' => array (
					'0' => 'Entitat promotora internacional' 
			) 
	);
	
	// Exported permission: clear feed_juridic feeds
	$permissions [] = array (
			'name' => 'clear feed_juridic feeds',
			'roles' => array (
					'0' => 'Entitat promotora juridic' 
			) 
	);
	
	// Exported permission: clear feed_projectes feeds
	$permissions [] = array (
			'name' => 'clear feed_projectes feeds',
			'roles' => array (
					'0' => 'Entitat promotora projectes' 
			) 
	);
	
	// Exported permission: clear feed_social feeds
	$permissions [] = array (
			'name' => 'clear feed_social feeds',
			'roles' => array (
					'0' => 'Entitat promotora social' 
			) 
	);
	
	// Exported permission: create feed_ambiental content
	$permissions [] = array (
			'name' => 'create feed_ambiental content',
			'roles' => array () 
	);
	
	// Exported permission: create feed_comunitari content
	$permissions [] = array (
			'name' => 'create feed_comunitari content',
			'roles' => array (
					'0' => 'Entitat promotora comunitari' 
			) 
	);
	
	// Exported permission: create feed_cultural content
	$permissions [] = array (
			'name' => 'create feed_cultural content',
			'roles' => array (
					'0' => 'Entitat promotora cultural' 
			) 
	);
	
	// Exported permission: create feed_economic content
	$permissions [] = array (
			'name' => 'create feed_economic content',
			'roles' => array (
					'0' => 'Entitat promotora economic' 
			) 
	);
	
	// Exported permission: create feed_formacio content
	$permissions [] = array (
			'name' => 'create feed_formacio content',
			'roles' => array (
					'0' => 'Entitat promotora formacio' 
			) 
	);
	
	// Exported permission: create feed_informatic content
	$permissions [] = array (
			'name' => 'create feed_informatic content',
			'roles' => array (
					'0' => 'Entitat promotora informatic' 
			) 
	);
	
	// Exported permission: create feed_internacional content
	$permissions [] = array (
			'name' => 'create feed_internacional content',
			'roles' => array (
					'0' => 'Entitat promotora internacional' 
			) 
	);
	
	// Exported permission: create feed_juridic content
	$permissions [] = array (
			'name' => 'create feed_juridic content',
			'roles' => array (
					'0' => 'Entitat promotora juridic' 
			) 
	);
	
	// Exported permission: create feed_portada content
	$permissions [] = array (
			'name' => 'create feed_portada content',
			'roles' => array (
					'0' => 'Entitat administradora' 
			) 
	);
	
	// Exported permission: create feed_projectes content
	$permissions [] = array (
			'name' => 'create feed_projectes content',
			'roles' => array (
					'0' => 'Entitat promotora projectes' 
			) 
	);
	
	// Exported permission: create feed_social content
	$permissions [] = array (
			'name' => 'create feed_social content',
			'roles' => array (
					'0' => 'Entitat promotora social' 
			) 
	);
	
	// Exported permission: create node_feeder content
	$permissions [] = array (
			'name' => 'create node_feeder content',
			'roles' => array () 
	);
	
	// Exported permission: create portada_node_feeder content
	$permissions [] = array (
			'name' => 'create portada_node_feeder content',
			'roles' => array () 
	);
	
	// Exported permission: delete any feed_ambiental content
	$permissions [] = array (
			'name' => 'delete any feed_ambiental content',
			'roles' => array () 
	);
	
	// Exported permission: delete any feed_comunitari content
	$permissions [] = array (
			'name' => 'delete any feed_comunitari content',
			'roles' => array (
					'0' => 'Entitat promotora comunitari' 
			) 
	);
	
	// Exported permission: delete any feed_cultural content
	$permissions [] = array (
			'name' => 'delete any feed_cultural content',
			'roles' => array (
					'0' => 'Entitat promotora cultural' 
			) 
	);
	
	// Exported permission: delete any feed_economic content
	$permissions [] = array (
			'name' => 'delete any feed_economic content',
			'roles' => array (
					'0' => 'Entitat promotora economic' 
			) 
	);
	
	// Exported permission: delete any feed_formacio content
	$permissions [] = array (
			'name' => 'delete any feed_formacio content',
			'roles' => array (
					'0' => 'Entitat promotora formacio' 
			) 
	);
	
	// Exported permission: delete any feed_informatic content
	$permissions [] = array (
			'name' => 'delete any feed_informatic content',
			'roles' => array (
					'0' => 'Entitat promotora informatic' 
			) 
	);
	
	// Exported permission: delete any feed_internacional content
	$permissions [] = array (
			'name' => 'delete any feed_internacional content',
			'roles' => array (
					'0' => 'Entitat promotora internacional' 
			) 
	);
	
	// Exported permission: delete any feed_juridic content
	$permissions [] = array (
			'name' => 'delete any feed_juridic content',
			'roles' => array (
					'0' => 'Entitat promotora juridic' 
			) 
	);
	
	// Exported permission: delete any feed_portada content
	$permissions [] = array (
			'name' => 'delete any feed_portada content',
			'roles' => array (
					'0' => 'Entitat administradora' 
			) 
	);
	
	// Exported permission: delete any feed_projectes content
	$permissions [] = array (
			'name' => 'delete any feed_projectes content',
			'roles' => array (
					'0' => 'Entitat promotora projectes' 
			) 
	);
	
	// Exported permission: delete any feed_social content
	$permissions [] = array (
			'name' => 'delete any feed_social content',
			'roles' => array (
					'0' => 'Entitat promotora social' 
			) 
	);
	
	// Exported permission: delete any node_feeder content
	$permissions [] = array (
			'name' => 'delete any node_feeder content',
			'roles' => array () 
	);
	
	// Exported permission: delete any portada_node_feeder content
	$permissions [] = array (
			'name' => 'delete any portada_node_feeder content',
			'roles' => array () 
	);
	
	// Exported permission: delete own feed_ambiental content
	$permissions [] = array (
			'name' => 'delete own feed_ambiental content',
			'roles' => array () 
	);
	
	// Exported permission: delete own feed_comunitari content
	$permissions [] = array (
			'name' => 'delete own feed_comunitari content',
			'roles' => array () 
	);
	
	// Exported permission: delete own feed_cultural content
	$permissions [] = array (
			'name' => 'delete own feed_cultural content',
			'roles' => array () 
	);
	
	// Exported permission: delete own feed_economic content
	$permissions [] = array (
			'name' => 'delete own feed_economic content',
			'roles' => array () 
	);
	
	// Exported permission: delete own feed_formacio content
	$permissions [] = array (
			'name' => 'delete own feed_formacio content',
			'roles' => array () 
	);
	
	// Exported permission: delete own feed_informatic content
	$permissions [] = array (
			'name' => 'delete own feed_informatic content',
			'roles' => array () 
	);
	
	// Exported permission: delete own feed_internacional content
	$permissions [] = array (
			'name' => 'delete own feed_internacional content',
			'roles' => array () 
	);
	
	// Exported permission: delete own feed_juridic content
	$permissions [] = array (
			'name' => 'delete own feed_juridic content',
			'roles' => array () 
	);
	
	// Exported permission: delete own feed_portada content
	$permissions [] = array (
			'name' => 'delete own feed_portada content',
			'roles' => array () 
	);
	
	// Exported permission: delete own feed_projectes content
	$permissions [] = array (
			'name' => 'delete own feed_projectes content',
			'roles' => array () 
	);
	
	// Exported permission: delete own feed_social content
	$permissions [] = array (
			'name' => 'delete own feed_social content',
			'roles' => array () 
	);
	
	// Exported permission: delete own node_feeder content
	$permissions [] = array (
			'name' => 'delete own node_feeder content',
			'roles' => array () 
	);
	
	// Exported permission: delete own portada_node_feeder content
	$permissions [] = array (
			'name' => 'delete own portada_node_feeder content',
			'roles' => array () 
	);
	
	// Exported permission: edit any feed_ambiental content
	$permissions [] = array (
			'name' => 'edit any feed_ambiental content',
			'roles' => array () 
	);
	
	// Exported permission: edit any feed_comunitari content
	$permissions [] = array (
			'name' => 'edit any feed_comunitari content',
			'roles' => array (
					'0' => 'Entitat promotora comunitari' 
			) 
	);
	
	// Exported permission: edit any feed_cultural content
	$permissions [] = array (
			'name' => 'edit any feed_cultural content',
			'roles' => array (
					'0' => 'Entitat promotora cultural' 
			) 
	);
	
	// Exported permission: edit any feed_economic content
	$permissions [] = array (
			'name' => 'edit any feed_economic content',
			'roles' => array (
					'0' => 'Entitat promotora economic' 
			) 
	);
	
	// Exported permission: edit any feed_formacio content
	$permissions [] = array (
			'name' => 'edit any feed_formacio content',
			'roles' => array (
					'0' => 'Entitat promotora formacio' 
			) 
	);
	
	// Exported permission: edit any feed_informatic content
	$permissions [] = array (
			'name' => 'edit any feed_informatic content',
			'roles' => array (
					'0' => 'Entitat promotora informatic' 
			) 
	);
	
	// Exported permission: edit any feed_internacional content
	$permissions [] = array (
			'name' => 'edit any feed_internacional content',
			'roles' => array (
					'0' => 'Entitat promotora internacional' 
			) 
	);
	
	// Exported permission: edit any feed_juridic content
	$permissions [] = array (
			'name' => 'edit any feed_juridic content',
			'roles' => array (
					'0' => 'Entitat promotora juridic' 
			) 
	);
	
	// Exported permission: edit any feed_portada content
	$permissions [] = array (
			'name' => 'edit any feed_portada content',
			'roles' => array (
					'0' => 'Entitat administradora' 
			) 
	);
	
	// Exported permission: edit any feed_projectes content
	$permissions [] = array (
			'name' => 'edit any feed_projectes content',
			'roles' => array (
					'0' => 'Entitat promotora projectes' 
			) 
	);
	
	// Exported permission: edit any feed_social content
	$permissions [] = array (
			'name' => 'edit any feed_social content',
			'roles' => array (
					'0' => 'Entitat promotora social' 
			) 
	);
	
	// Exported permission: edit any node_feeder content
	$permissions [] = array (
			'name' => 'edit any node_feeder content',
			'roles' => array () 
	);
	
	// Exported permission: edit any portada_node_feeder content
	$permissions [] = array (
			'name' => 'edit any portada_node_feeder content',
			'roles' => array () 
	);
	
	// Exported permission: edit field_imatge_feed
	$permissions [] = array (
			'name' => 'edit field_imatge_feed',
			'roles' => array (
					'0' => 'Entitat administradora',
					'1' => 'Entitat promotora ambiental',
					'2' => 'Entitat promotora comunitari',
					'3' => 'Entitat promotora cultural',
					'4' => 'Entitat promotora economic',
					'5' => 'Entitat promotora formacio',
					'6' => 'Entitat promotora informatic',
					'7' => 'Entitat promotora internacional',
					'8' => 'Entitat promotora juridic',
					'9' => 'Entitat promotora projectes',
					'10' => 'Entitat promotora social' 
			) 
	);
	
	// Exported permission: edit own feed_ambiental content
	$permissions [] = array (
			'name' => 'edit own feed_ambiental content',
			'roles' => array () 
	);
	
	// Exported permission: edit own feed_comunitari content
	$permissions [] = array (
			'name' => 'edit own feed_comunitari content',
			'roles' => array () 
	);
	
	// Exported permission: edit own feed_cultural content
	$permissions [] = array (
			'name' => 'edit own feed_cultural content',
			'roles' => array () 
	);
	
	// Exported permission: edit own feed_economic content
	$permissions [] = array (
			'name' => 'edit own feed_economic content',
			'roles' => array () 
	);
	
	// Exported permission: edit own feed_formacio content
	$permissions [] = array (
			'name' => 'edit own feed_formacio content',
			'roles' => array () 
	);
	
	// Exported permission: edit own feed_informatic content
	$permissions [] = array (
			'name' => 'edit own feed_informatic content',
			'roles' => array () 
	);
	
	// Exported permission: edit own feed_internacional content
	$permissions [] = array (
			'name' => 'edit own feed_internacional content',
			'roles' => array () 
	);
	
	// Exported permission: edit own feed_juridic content
	$permissions [] = array (
			'name' => 'edit own feed_juridic content',
			'roles' => array () 
	);
	
	// Exported permission: edit own feed_portada content
	$permissions [] = array (
			'name' => 'edit own feed_portada content',
			'roles' => array () 
	);
	
	// Exported permission: edit own feed_projectes content
	$permissions [] = array (
			'name' => 'edit own feed_projectes content',
			'roles' => array () 
	);
	
	// Exported permission: edit own feed_social content
	$permissions [] = array (
			'name' => 'edit own feed_social content',
			'roles' => array () 
	);
	
	// Exported permission: edit own node_feeder content
	$permissions [] = array (
			'name' => 'edit own node_feeder content',
			'roles' => array () 
	);
	
	// Exported permission: edit own portada_node_feeder content
	$permissions [] = array (
			'name' => 'edit own portada_node_feeder content',
			'roles' => array () 
	);
	
	// Exported permission: import feed_ambiental feeds
	$permissions [] = array (
			'name' => 'import feed_ambiental feeds',
			'roles' => array (
					'0' => 'Entitat promotora ambiental' 
			) 
	);
	
	// Exported permission: import feed_comunitari feeds
	$permissions [] = array (
			'name' => 'import feed_comunitari feeds',
			'roles' => array (
					'0' => 'Entitat promotora comunitari' 
			) 
	);
	
	// Exported permission: import feed_cultural feeds
	$permissions [] = array (
			'name' => 'import feed_cultural feeds',
			'roles' => array () 
	);
	
	// Exported permission: import feed_de_portada feeds
	$permissions [] = array (
			'name' => 'import feed_de_portada feeds',
			'roles' => array (
					'0' => 'Entitat administradora' 
			) 
	);
	
	// Exported permission: import feed_econ_mic feeds
	$permissions [] = array (
			'name' => 'import feed_econ_mic feeds',
			'roles' => array (
					'0' => 'Entitat promotora economic' 
			) 
	);
	
	// Exported permission: import feed_formacio feeds
	$permissions [] = array (
			'name' => 'import feed_formacio feeds',
			'roles' => array (
					'0' => 'Entitat promotora formacio' 
			) 
	);
	
	// Exported permission: import feed_informatic feeds
	$permissions [] = array (
			'name' => 'import feed_informatic feeds',
			'roles' => array (
					'0' => 'Entitat promotora informatic' 
			) 
	);
	
	// Exported permission: import feed_internacional feeds
	$permissions [] = array (
			'name' => 'import feed_internacional feeds',
			'roles' => array (
					'0' => 'Entitat promotora internacional' 
			) 
	);
	
	// Exported permission: import feed_juridic feeds
	$permissions [] = array (
			'name' => 'import feed_juridic feeds',
			'roles' => array (
					'0' => 'Entitat promotora juridic' 
			) 
	);
	
	// Exported permission: import feed_projectes feeds
	$permissions [] = array (
			'name' => 'import feed_projectes feeds',
			'roles' => array (
					'0' => 'Entitat promotora projectes' 
			) 
	);
	
	// Exported permission: import feed_social feeds
	$permissions [] = array (
			'name' => 'import feed_social feeds',
			'roles' => array (
					'0' => 'Entitat promotora social' 
			) 
	);
	
	// Exported permission: view field_imatge_feed
	$permissions [] = array (
			'name' => 'view field_imatge_feed',
			'roles' => array (
					'0' => 'Entitat administradora',
					'1' => 'Entitat promotora ambiental',
					'2' => 'Entitat promotora comunitari',
					'3' => 'Entitat promotora cultural',
					'4' => 'Entitat promotora economic',
					'5' => 'Entitat promotora formacio',
					'6' => 'Entitat promotora informatic',
					'7' => 'Entitat promotora internacional',
					'8' => 'Entitat promotora juridic',
					'9' => 'Entitat promotora projectes',
					'10' => 'Entitat promotora social',
					'11' => 'anonymous user',
					'12' => 'authenticated user' 
			) 
	);
	
	return $permissions;
}
