<?php

/**
 * @file
 * Primarily Drupal hooks.
 */

/**
 * Implementatation of hook_detect_mobile_device().
 */
function mt_browscap_detect_mobile_device() {
  // Assume that the site visitor is using a desktop browser until we can prove
  // otherwise
  $device_information = array(
    'type' => 'desktop',
    'group' => '',
  );

  // Make sure the browscap module is loaded, so we can use it below.
  // This is necessary in some cases because this code runs before all
  // modules are loaded.
  drupal_load('module', 'browscap');
  
  // Get Browscap information about the current user agent
  $user_agent = browscap_get_browser();

  // Check the browscap information to see if the current user agent is
  // flagged as a mobile device.
  // For some reason, this might be returned as the string value
  // 'false', which of course evaluates as true.
  if (!empty($user_agent['ismobiledevice']) && $user_agent['ismobiledevice'] !== 'false') {
  	$device_information['type'] = 'mobile';
  }

  // Get the currently defined device groups
  $groups = mt_browscap_device_groups_info();

  // Check if the current user agent name can be found within the list of
  // device groups
  if (isset($user_agent['browser']) && in_array($user_agent['browser'], $groups)) {
    $device_information['group'] = array_search($user_agent['browser'], $groups);
  }

  return $device_information;
}

/**
 * Implementatation of hook_device_groups_info().
 */
function mt_browscap_device_groups_info() {
  return array(
    'android' => 'Android',
    'blackberry' => 'BlackBerry',
    'ipad' => 'iPad',
    'iphone' => 'iPhone',
    'ipod' => 'iPod',
    'opera_mini' => 'Opera Mini',
    'windows_phone' => 'Windows Phone',
  );
}
