<?php
// $Id: 

/**
 * @file
 * Services most used and supported from the start by Service Links module
 */

/**
 * Implementation of hook_service_links().
 */
function xarxanet_services_service_links() {
  $links = array();

  $links['flinkin'] = array(
    'name' => 'Flinkin',
    'description' => t('Bookmark this post on Flinkin.'),
    'link' => 'http://www.flinkin.com/api/addLink.php?url=<encoded-url>',
  );
  
  $links['diigo'] = array(
    'name' => 'Diigo',
    'description' => t('Bookmark this post on Diigo.'),
    'link' => 'http://www.diigo.com/post?url=<encoded-url>&title=<encoded-title>',
  );
  

  return $links;
}
