<?php
/**
 * @file
 * Provides a context reaction to change the default front page.
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function context_reaction_site_frontpage_ctools_plugin_api($module, $api) {
  if ('context' === $module && 'plugins' === $api) {
    return array('version' => 3);
  }
}

/**
 * Implements hook_boot().
 */
function context_reaction_site_frontpage_boot() {
  drupal_bootstrap(DRUPAL_BOOTSTRAP_FULL);
  if (path_is_admin(current_path())) {
    return FALSE;
  }

  drupal_load('module', 'context');
  if ($plugin = context_get_plugin('reaction', 'context_reaction_site_frontpage')) {
    $plugin->execute();
  }
}

/**
 * Implements hook_context_plugins().
 */
function context_reaction_site_frontpage_context_plugins() {
  return array(
    'context_reaction_site_frontpage' => array(
      'handler' => array(
        'path'   => drupal_get_path('module', 'context_reaction_site_frontpage') . '/plugins',
        'file'   => 'context_reaction_site_frontpage.inc',
        'class'  => 'context_reaction_site_frontpage',
        'parent' => 'context_reaction',
      ),
    ),
  );
}

/**
 * Implements hook_context_registry().
 */
function context_reaction_site_frontpage_context_registry() {
  return array(
    'reactions' => array(
      'context_reaction_site_frontpage' => array(
        'title'  => t('Front page'),
        'plugin' => 'context_reaction_site_frontpage',
      ),
    ),
  );
}

/**
 * Element validate callback for the site front page field.
 *
 * Ensure that the path given is not <front> or an external URL
 * and that it exists.
 *
 * @see context_reaction_site_frontpage::execute().
 */
function context_reaction_site_frontpage_validate($element, &$form_state) {
  $plugins     = $form_state['values']['reactions']['plugins'];
  $link_path   = $plugins['context_reaction_site_frontpage']['site_frontpage'];
  $normal_path = drupal_get_normal_path($link_path);
  if ($link_path != $normal_path) {
    drupal_set_message(t(
      'The menu system stores system paths only, but will use the URL alias for display. %link_path has been stored as %normal_path',
      array(
        '%link_path'   => $link_path,
        '%normal_path' => $normal_path,
      )
    ));
    $link_path = $normal_path;
  }

  if (
    '<front>' === $link_path || url_is_external($link_path) ||
    (!drupal_valid_path($link_path) && !drupal_lookup_path('source', $link_path))
  ) {
    form_set_error(
      'site_frontpage',
      t("The path '%path' is either invalid or you do not have access to it.",
      array('%path' => $link_path))
    );
  }
}

