<?php
// $ID$

function cercador_recursos_menu() {
	
	$items['projectes/recursos/cercador'] = array( //es posible que es tingui que duplicar
		'title' => t('Cercador de recursos'),
		'page callback' => 'cercador_recursos_cercador',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	$items['juridic/recursos/cercador'] = array( //es posible que es tingui que duplicar
		'title' => t('Cercador de recursos'),
		'page callback' => 'cercador_recursos_cercador',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	$items['economic/recursos/cercador'] = array( //es posible que es tingui que duplicar
		'title' => t('Cercador de recursos'),
		'page callback' => 'cercador_recursos_cercador',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	$items['formacio/recursos/cercador'] = array( //es posible que es tingui que duplicar
		'title' => t('Cercador de recursos'),
		'page callback' => 'cercador_recursos_cercador',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	$items['informatic/recursos/cercador'] = array( //es posible que es tingui que duplicar
		'title' => t('Cercador de recursos'),
		'page callback' => 'cercador_recursos_cercador',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	$items['recursos/cercador'] = array( //es posible que es tingui que duplicar
		'title' => t('Cercador de recursos'),
		'page callback' => 'cercador_recursos_cercador',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	return $items;
}

function cercador_recursos_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL)
{
	switch($op){
		case 'view':
			$show = false;
			if($node->nid==60) //cal duplicar per cada portal d'assessorament.
			{
				$_GET['projectes']=1;
				$show=true;
			}
			elseif($node->nid==154)
			{
				$_GET['formacio']=1;
				$show=true;
			}			
			elseif($node->nid==155)
			{
				$_GET['juridic']=1;
				$show=true;
			}elseif($node->nid==156)
			{
				$_GET['economic']=1;
				$show=true;
			}
			elseif($node->nid==157)
			{
				$_GET['informatic']=1;
				$show=true;
			}
			elseif($node->nid==213)
			{
				$show=true;
			}
			if($show)
			{
				$fieldset = array(
					'#type' => 'fieldset',
					'#title' => t('Cercador'),
					'#collapsible' => TRUE,
					'#collapsed' => FALSE,
					'#value' => drupal_get_form('cercador_recursos_cercador_form'),
				);
				
        if($node->nid==213)
        {
          $node->content['cercador_recursos']=array(
            "#value"=>theme('fieldset', $fieldset),
            "#weight"=>"100");
        }else{
          $node->content['cercador_recursos']=array(
            "#value"=>theme('fieldset', $fieldset),
            "#weight"=>"0");
        }
			}
			
		break;
	}
}

function cercador_recursos_cercador($resultado=""){
  
  $fieldset = array(
					'#type' => 'fieldset',
					'#title' => t('Cercador'),
					'#collapsible' => TRUE,
					'#collapsed' => FALSE,
					'#value' => drupal_get_form('cercador_recursos_cercador_form'),
				);
  $return = theme('fieldset', $fieldset); 
  
  if (isset($_GET['form_id'])) {
		
		if(cercador_recursos_cercador_form_validate())
		{
			$results = cercador_recursos_cercador_form_submit();
			//print sizeof($results['search']);
			
			$nodes = $results['search'];
		
			if(sizeof($nodes)>0)
			{			
				$return.="<div class='e_news e_news_votes'><ul class='items'>";
				
				foreach($nodes as $node)
				{
					$return.=theme('search_result_recursos', $node);
					
				}
				
				$return.="</ul></div>";
			}else{
				$return.=t("Cap resultat");
			}
		}
	
  }
  
  return $return;
}



function cercador_recursos_cercador_form(&$form_state){
	$form = array(
    '#action' => $_SERVER['REQUEST_URI']."/cercador",
	'#method' => 'get',
  );
	
	
	$form['buscar'] = array(
		'#type' => 'textfield',
		'#title' => t('Text a cercar'),
		'#description' => t(utf8_encode("Introdueix aquí el text a cercar")),
		'#default_value'=> $_GET['buscar'],
		'#required' => TRUE,
	);
	$form['div0'] = array('#type' => 'markup', '#value' => '<div id="cercador-recursos">');
	$form['projectes'] = array(
		'#type'=>'checkbox',
		'#title' =>t(utf8_encode('Projectes')),
		'#default_value'=> $_GET['projectes'],
	);
	$form['formacio'] = array(
		'#type'=>'checkbox',
		'#title' =>t(utf8_encode('Formació')),
		'#default_value'=> $_GET['formacio'],
	);
	$form['juridic'] = array(
		'#type'=>'checkbox',
		'#title' =>t(utf8_encode('Jurídic')),
		'#default_value'=> $_GET['juridic'],
	);
	$form['economic'] = array(
		'#type'=>'checkbox',
		'#title' =>t(utf8_encode('Econòmic')),
		'#default_value'=> $_GET['economic'],
	);
	$form['informatic'] = array(
		'#type'=>'checkbox',
		'#title' =>t(utf8_encode('Informàtic')),
		'#default_value'=> $_GET['informatic'],
	);
  $form['general'] = array(
		'#type'=>'checkbox',
		'#title' =>t(utf8_encode('General')),
		'#default_value'=> $_GET['general'],
	);
  $form['div1'] = array('#type' => 'markup', '#value' => '</div>');
	$form['submit']=array(
		'#type'=>'submit',
		'#value' =>t('Cercar')
		);
	
  return $form;
}



function cercador_recursos_cercador_form_validate(){
	
	$validate=true;
	
	if($_GET['buscar']=="")
	{
		_set_error('buscar', "No s'ha introduït un valor en el camp de cerca");
		$validate=false;
	}
	
	return $validate;
	
}


function cercador_recursos_cercador_form_submit(){ //its custom, not drupal way. 
	
	$array = array();
	$map = "";
	$coords = array();
	
	$date = _formate_date($_GET['init_date']['year'],$_GET['init_date']['month'],$_GET['init_date']['day']);
			
	$mapa = ($_GET['mapa']=='si');
		
	
		
	$a_text = preg_split("[ ]", $_GET['buscar']);
		
			/* Select nodes witch have the key words (using drupal search index)*/
			$query = "SELECT n.nid
			FROM {node n, search_index si} 
			WHERE n.nid = si.sid
				AND n.status = 1";
			

			
			$types = array();
			if($_GET['projectes']==1) $types[]="recurs_projectes";
			if($_GET['formacio']==1) $types[]="recurs_formacio";
			if($_GET['juridic']==1) $types[]="recurs_juridic";
			if($_GET['economic']==1) $types[]="recurs_economic";
			if($_GET['informatic']==1) $types[]="recurs_informatic";
      if($_GET['general']==1) $types[]="recurs_general";
			
			if(sizeof($types)>0)
			{
				$query.=" AND (n.type ='"._scape($types[0])."'";
			
				for($i=1;$i<sizeof($types);$i++)
				{
					$query.=" OR n.type = '"._scape($types[$i])."'";
				}
				$query.=")";
			}
			else
			{
				$query.=" AND n.type LIKE 'recurs_%'";
			}
			
			
			$query.=" AND (si.word ='"._scape($a_text[0])."'";
			
			for($i=1;$i<sizeof($a_text);$i++)
			{
				$query.=" OR si.word = '"._scape($a_text[$i])."'";
			}
	
			$query.=")";
		
	
	$result = db_query($query);

	$i=0;
	while ($res = db_fetch_array($result)){
		
		$node = node_build_content(node_load($res['nid']));
		$array[]=$node;
	}
		
	
	return array('search'=>$array, 'query' => $query,);
}


function cercador_recursos_theme() {
  return array(
    // as in 'theme('verbose_method',...)
    'search_result_recursos' => array(
      // routes to file exampleModule/spanks-box-thing.tpl.php or [YOUR ACTIVE THEME DIRECTORY]/spanky-box-thing.tpl.php
      'template' => 'search-result-recursos',
      // these variables must be called in the theme function, and will appear in the template as $title, $body, $link
      'arguments' => array(
		'node' => null, 
      ),
    ),);
}






	

