<?php

/**
 * Implements hook_menu().
 */
function tothomweb_sitemap_menu() {    
  $items['mapa-web'] = array(
    'title' => t('Mapa web'),
    'page callback' => 'tothomweb_sitemap_preprocess_page', 
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements the callback.
 */
function tothomweb_sitemap_preprocess_page(&$vars) {
  if (current_path() == 'mapa-web') {
    $menu_name = 'menu_main_links_source';
    $params = 'main-menu';
    $menu = variable_get($menu_name, $params);
    $content = render(tothomweb_sitemap_menu_tree($menu));
    
    $vars['page']['content'] = $content;
    return $vars;
  }
}

/**
 * Helper function that returns a menu built for 
 * rendering as a dropdown menu.
 */
function tothomweb_sitemap_menu_tree($menu_name, $options = array()) {
  $menu_tree = menu_build_tree($menu_name, $options);
  $element = menu_tree_output($menu_tree);
  $element['#theme_wrappers'] = array();
  foreach (element_children($element) as $mlid) {
    tothomweb_sitemap_main_menu_link_process($element[$mlid]);
  }
  return $element;
}

/**
 * Helper function that suggests the the menu link 
 * to render with a dropdown.
 */
function tothomweb_sitemap_main_menu_link_process(&$element) {
  $element['#theme'] = 'menu_link__main';
  if (!empty($element['#below'])) {
    foreach (element_children($element['#below']) as $mlid) {
      tothomweb_sitemap_main_menu_link_process($element['#below'][$mlid]);
    }
  }
}
