<?php

function xarxanet_feeders_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL){

  switch($node->type){
    case 'node_feeder':
      if($op == 'presave'){
        $node_parent = node_load($node->feeds_node_item->feed_nid);
        $node->field_imatge_feed = $node_parent->field_imatge_feed;
      }elseif($op == 'view'){

      }
    case 'portada_node_feeder':
      if($op == 'presave'){
        $node_parent = node_load($node->feeds_node_item->feed_nid);
        $node->field_imatge_feed = $node_parent->field_imatge_feed;
      }
      break;
  }
}