<?php

// $Id$
function taxonomy_checker_perm(){
    return array('admin taxonomy checker');
}


function taxonomy_checker_taxonomy($op, $type, $array = NULL){
    if($op == 'insert' && $type == 'term')
    {
        if(_taxonomy_checker_is_in_list($array['vid'])){
            $result = db_query("INSERT INTO {taxonomy_checks} (tid,name,vid) VALUES (%d,'%s',%d)",$array['tid'],$array['name'],$array['vid']);
            if(!$result) drupal_set_message(t('There was an error on Taxonomy Checker when inserting this term on the database'));
        }else{
            drupal_set_message(t("El terme no necessita ser comprovat",array(),'ca'));
        }
    }
}

function taxonomy_checker_menu(){
    $items = array();
    
    $items['taxonomy/lastitems'] = array(
        'title' => 'Last Texonomy Terms',
        'page callback' => 'taxonomy_checker_last_items_added_page',
        'access arguments' => array('admin taxonomy checker'),
        'type' => MENU_NORMAL_ITEM,
    );
    
    $items['admin/settings/taxonomy_checker'] = array(
        'title' => 'Taxonomy Checker Configuration',
        'page callback' => 'taxonomy_checker_config_page',
        'access arguments' => array('admin taxonomy checker'),
        'type' => MENU_NORMAL_ITEM,
    );
    
    return $items;
}

function _taxonomy_checker_is_in_list($vid){
    $vids = variable_get('vids_checked',array());
    return in_array($vid,$vids);
}

function taxonomy_checker_last_items_added_page(){

    return drupal_get_form('taxonomy_checker_last_terms_form');
}

function taxonomy_checker_config_page(){
    return drupal_get_form('taxonomy_checker_config_form');
}

function taxonomy_checker_config_form($form_state){
    $form = array();
    $vocabularies = taxonomy_get_vocabularies();
    foreach($vocabularies as $key => $vocs){
        $vids[$key] = $vocs->name;
    }
    
    $form['vids'] = array(
        '#type' => 'checkboxes',
        '#title' => t('Taxonomies to be checked'),
        '#default_value' => variable_get('vids_checked',array()),
        '#options' => $vids,
    );
    
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Save'),
    );

    return $form;
}

function taxonomy_checker_config_form_submit($form,&$form_state){
    variable_set('vids_checked',$form_state['values']['vids']);
    drupal_set_message(t('Your settings have been saved.'));
}

function taxonomy_checker_last_terms_form($form_state){
    $form = array();
    
    $result = db_query("SELECT * FROM {taxonomy_checks} ORDER BY vid");
    $i=0;
    $j=0;
    if($res = db_fetch_object($result))
    {
        $vid = $res->vid;
        $vidname = db_fetch_object(db_query("SELECT name FROM {vocabulary} WHERE vid = %d",$res->vid))->name;
        $form['vocabulary'.$j] = array(
            '#type' => 'fieldset',
            '#title' => $vidname,
            '#collapsible' => TRUE,
            '#collapsed' => FALSE,
        );
        $form['vocabulary'.$j]['element'.$i] = array(
            '#type' => 'checkbox',
            '#title' => l($res->name,'admin/content/taxonomy_manager/voc/'.$res->vid."/".$res->tid,array('attributes'=>array('target'=>'blank_'))),
            '#default_value' => 0,
            '#return_value' => $res->tid,
        );
        $i++;
    }
    
    
    while($res = db_fetch_object($result)){
        if($res->vid == $vid)
        {
            $form['vocabulary'.$j]['element'.$i] = array(
                '#type' => 'checkbox',
                '#title' => l($res->name,'admin/content/taxonomy_manager/voc/'.$res->vid."/".$res->tid,array('attributes'=>array('target'=>'blank_'))),
                '#default_value' => 0,
                '#return_value' => $res->tid,
            );
        }else{
            $j++;
            $vid = $res->vid;
            $vidname = db_fetch_object(db_query("SELECT name FROM {vocabulary} WHERE vid = %d",$res->vid))->name;
            $form['vocabulary'.$j] = array(
                '#type' => 'fieldset',
                '#title' => $vidname,
                '#collapsible' => TRUE,
                '#collapsed' => FALSE,
            );
            $form['vocabulary'.$j]['element'.$i] = array(
                '#type' => 'checkbox',
                '#title' => l($res->name,'admin/content/taxonomy_manager/voc/'.$res->vid."/".$res->tid,array('attributes'=>array('target'=>'blank_'))),
                '#default_value' => 0,
                '#return_value' => $res->tid,
            );
        }
        $i++;
    }
    
    if($i>0)
    {
        $form['numberitems'] = array(
            '#type' => 'hidden',
            '#value' => $i
        );
        
        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => t('Save'),
        );
    }else{
        $form['message'] = array(
            '#value' => t('There are no terms to be moderated'),
        );
    }
    
    return $form;

}

function taxonomy_checker_last_terms_form_submit($form,&$form_state){
    $numitems = $form_state['values']['numberitems'];
    if($numitems>0){
        while($numitems >= 0){
            if($form_state['values']['element'.$numitems]!=0){
                db_query("DELETE FROM {taxonomy_checks} WHERE tid =%d",$form_state['values']['element'.$numitems]);
                drupal_set_message('El terme '.$form_state['values']['element'.$numitems]." ha estat moderat");
            }
            $numitems--;
        }
    }
}