<?php

if ($_SERVER['HTTP_HOST'] == 'xarxanet.local') {
	define('AGENDA_URL', 'agenda-dev');
}
else {
	define('AGENDA_URL', 'agenda');
}

/**
 * Implements hook_menu().
 *
 * @return  $items
 */
function tothomweb_agenda_menu() {
		$items[AGENDA_URL] = array(
		'title' => 'Agenda',
		'page callback' => 'drupal_get_form', 
		'page arguments' => array('tothomweb_agenda_form'), 
		'access arguments' => array(), 
		'type' => MENU_NORMAL_ITEM,
	);
	return $items;
}

/**
 * Implements hook_form().
 *
 * @param	  $form
 * 					Array containing the form's basic data & structure.
 * 
 * @param	  $form_state
 * 					Array containing the form submitted data and other cool stuff.
 * 
 * @return  $form
 */
function tothomweb_agenda_form($form, &$form_state) {
	/**
	 * Set the method of the form to 'GET', so the hook_form_submit() is not
	 * required in this form. 
	 * 
	 * In addition, some useless Drupal default parameters are removed from the url, by
	 * altering the form after it's built, in order to get cleaner urls. I.e.: Notice 
	 * that the '#name' attribute of the submit is set to an empty string,
	 * in order to avoid showing the 'op' paramenter in the url argument's list.
	 * 
	 * @see tothomweb_agenda_form_alter()
	 * 
	 * @see https://drupal.stackexchange.com/a/192381
	 */

	$form['#method'] = 'GET';
	$form['#after_build'][] = 'tothomweb_agenda_form_alter';

	// Filter's Area

	$form['filters_area'] = array(
		'#type' => 'container',
		'#attributes' => array(
			'class' => array('row'),
		),
		'#prefix' => '<div class="container agenda-header">',
		'#suffix' => '</div>',
	);

	$form['filters_area']['filters_box'] = array(
		'#type' => 'container',
		'#attributes' => array(
			'id' => 'filters-box',
			'class' => array('filters-box'),
		),
		'#prefix' => '<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-6 col-md-offset-3">',
		'#suffix' => '</div>',
	);

	$form['filters_area']['filters_box']['filters_header'] = array(
		'#type' => 'markup',
		'#markup' => tothomweb_agenda_build_type_filters_markup(),
	);

	$form['filters_area']['filters_box']['filters_body'] = array(
		'#type' => 'container',
		'#attributes' => array(
			'class' => array('row'),
		),
		'#prefix' => '<div class="filters-body">',
		'#suffix' => '</div>',
	);

	$form['filters_area']['filters_box']['filters_body']['search'] = array(
		'#type' => 'textfield', 
		'#title' => '<span class="sr-only">' . t('Cercar per paraula o paraules clau') . '</span>',
		'#attributes' => array(
			'placeholder' => t('Cercar per paraula clau'),
		),
		'#default_value' => (isset($_GET['search'])) ? $_GET['search'] : '', 
		'#size' => 60, 
		'#maxlength' => 128,
		'#prefix' => '<div class="col-xs-12 col-sm-4">',
		'#suffix' => '</div>',
	);

	$form['filters_area']['filters_box']['filters_body']['date'] = array(
		'#type' => 'textfield', 
		'#title' => '<span class="sr-only">' . t('Cercar per data') . '</span>',
		'#attributes' => array(
			'placeholder' => t('Cercar per data'),
		),
		'#default_value' => (isset($_GET['date'])) ? $_GET['date'] : date('d/m/Y', time()), 
		'#size' => 60, 
		'#maxlength' => 128,
		'#prefix' => '<div class="col-xs-12 col-sm-4">',
		'#suffix' => '</div>',
	);

	$form['filters_area']['filters_box']['filters_body']['location'] = array(
		'#type' => 'textfield', 
		'#title' => '<span class="sr-only">' . t('Cercar per municipi') . '</span>',
		'#attributes' => array(
			'placeholder' => t('Cercar per municipi'),
		),
		'#default_value' => (isset($_GET['location'])) ? $_GET['location'] : '', 
		'#size' => 60, 
		'#maxlength' => 128,
		'#prefix' => '<div class="col-xs-12 col-sm-4">',
		'#suffix' => '</div>',
	);

	$form['filters_area']['filters_box']['filters_footer'] = array(
		'#type' => 'container',
		'#attributes' => array(
			'class' => array('row'),
		),
		'#prefix' => '<div class="filters-footer">',
		'#suffix' => '</div>',
	);

	$form['filters_area']['filters_box']['filters_footer']['mode'] = array(
		'#type' => 'radios',
		'#title' => '<span class="sr-only">' . t('Selecciona la') . ' </span>' . t('Modalitat') . ' <span class="sr-only">' . t('de l\'esdeveniment') . '</span>',
		'#default_value' => (isset($_GET['mode'])) ? $_GET['mode'] : 'all',
		'#options' => tothomweb_agenda_build_mode_options(),
		'#prefix' => '<div class="col-xs-12 col-sm-8">',
		'#suffix' => '</div>',
	);

	$form['filters_area']['filters_box']['filters_footer']['mode']['new'] = array(
		'#type' => 'markup',
		'#markup' => '<a class="add-event" href="/node/add/event">' . t('Publica un nou esdeveniment') . '</a>',
		'#weight' => 11, // Drupal's default value is 10
	);

	$form['filters_area']['filters_box']['filters_footer']['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Cercar'),
		'#prefix' => '<div class="col-xs-12 col-sm-4">',
		'#suffix' => '</div>',
	);

	// Results' Area

	$form['results_area'] = array(
		'#type' => 'container',
		'#attributes' => array(
			'id' => array('results'),
			'class' => array('row'),
		),
		'#prefix' => '<div class="container agenda-body">',
		'#suffix' => '</div>',
	);

	$form['results_area']['grid'] = array(
		'#type' => 'markup',
		'#markup' => tothomweb_agenda_query_results(),
	);

	return $form;
}

/**
 * Implements hook_form_validate().
 */
function tothomweb_agenda_form_validate($form, &$form_state) {

}

/**
 * Helper function that build the query, given a set of url parameters.
 */
function tothomweb_agenda_query_results($form, &$form_state) {
	return 'Results here...';
}

/**
 * Implements hook_form_alter().
 * 
 * Remove some useless Drupal parameters from the url,
 * after the form has been built.
 *
 * @see https://drupal.stackexchange.com/a/192381
 *
 * @param   object  $form
 * 
 * @return  object  $form
 */

function tothomweb_agenda_form_alter($form) {
	unset($form['form_token']);
	unset($form['form_build_id']);
	unset($form['form_id']);
	return $form;
}

/**
 * Helper function that builds a small markup with the links
 * of the filters' header.
 */
function tothomweb_agenda_build_type_filters_markup() {
	// Set filter status by checking url parameters
	$all_status = (!isset($_GET['type']) || $_GET['type'] == 'all') ? ' active' : '';
	$events_status = (isset($_GET['type']) && $_GET['type'] == 'events') ? ' active' : '';
	$courses_status = (isset($_GET['type']) && $_GET['type'] == 'courses') ? ' active' : '';
	// Build the markup, including filters statuses
	$output  = '<div class="filters-header">';
	$output .= '<a class="type-filter' . $all_status . '" href="/' . AGENDA_URL . '?type=all">Tots</a>';
	$output .= '<a class="type-filter' . $events_status . '" href="/' . AGENDA_URL . '?type=events">Actes</a>';
	$output .= '<a class="type-filter' . $courses_status . '" href="/' . AGENDA_URL . '?type=courses">Cursos</a>';
	$output .= '</div>';
	return $output;
}

/**
 * Helper function that builds an array of options for
 * the 'Modalitat' radios.
 */
function tothomweb_agenda_build_mode_options() {
	$options  = array(
		'all' => t('Qualsevol'),
		'online' => t('En línia'),
	);
	return $options;
}
