<?php

/**
 * Implements hook_menu().
 *
 * @return  $items
 */
function tothomweb_agenda_menu() {
		$items['agenda-dev'] = array(
		'title' => 'Agenda',
		'page callback' => 'drupal_get_form', 
		'page arguments' => array('tothomweb_agenda_form'), 
		'access arguments' => array(), 
		'type' => MENU_NORMAL_ITEM,
	);
	return $items;
}

/**
 * Implements hook_form().
 *
 * @return  $form
 */
function tothomweb_agenda_form($form, &$form_state) {
	$form = array();

	return $form;
}

/**
 * Implements hook_form_validate().
 */
function tothomweb_agenda_form_validate($form, &$form_state) {

}

/**
 * Implements hook_form_submit().
 */
function tothomweb_agenda_form_submit($form, &$form_state) {

}
