<?php
function xarxanet_gestor_menu() {
	
		$items['gestio/continguts'] = array(
		'title' => 'Gestor Continguts',
		'page callback' => 'xarxanet_gestor_continguts_view', 
		'access arguments' => array('gestio continguts propis'), 
		'type' => MENU_NORMAL_ITEM,
		
		
		
	);
	return $items;
}
function xarxanet_gestor_continguts_view()
{
	global $user;
	
	if(isset($user))
	{
    $view = views_get_view("contingut_propi");
    $view->set_arguments(array($user->name));
    $view->set_display("Default");
  
    return $view->preview();
	}
	else return "";
}

function xarxanet_gestor_perm(){
  return array('gestio continguts propis');
}

