<?php
/**
 * @file
 * Module to define a sending time for each simplenews issue.
 */

/**
 * NEWSLETTER SEND COMMAND
 * Extends the options in Simplenews module.
 */
define('SIMPLENEWS_COMMAND_SENDING_TIME', 5);
define('SIMPLENEWS_COMMAND_NOT_SEND_YET', 6);

/**
 * Implementation of hook_perm().
 */
function simplenews_sending_time_perm() {
	return array('define issue sending time');
}

/**
 * Implementation of hook_form_FORM_ID_alter().
 * Add sending time field to the newsletter edit form.
 */
function simplenews_sending_time_form_simplenews_node_tab_send_form_alter(&$form, &$form_state) {
	global $user;
	
	if (user_access('define issue sending time')) {
		
		// Add js
		drupal_add_js(drupal_get_path('module', 'simplenews_sending_time') . '/simplenews_sending_time.js', 'module', 'header', FALSE, FALSE, TRUE);
		
		// Set the default values.
		$form['#submit'][] = "simplenews_sending_time_submit";
		$result = db_query("SELECT * FROM {simplenews_sending_time} WHERE nid = %d", arg(1));
		$row = db_fetch_array($result);
		$time = ($row) ? $row['time'] : $_SERVER['REQUEST_TIME'];
		$time = date_make_date($time, date_default_timezone_name(), DATE_UNIX);

		// Add further commands to the 'Send action' radio buttons.
		$form['simplenews']['send']['#options'][SIMPLENEWS_COMMAND_SENDING_TIME] = t('Send newsletter on defined time');
		$form['simplenews']['send']['#options'][SIMPLENEWS_COMMAND_NOT_SEND_YET] = t('Not send yet');
		$form['simplenews']['send']['#default_value'] = ($row) ? SIMPLENEWS_COMMAND_SENDING_TIME : SIMPLENEWS_COMMAND_NOT_SEND_YET;

		$form['simplenews']['sending_time'] = array(
				'#type' => 'fieldset',
				'#title' => t('Sending time'),
				'#attributes' => array('class' => 'sending_time'),
				'#collapsible' => FALSE,
				'#collapsed' => FALSE,
				'#tree' => TRUE,
		);

		// Translate formatted date results.
		$time_str = date_format_date($time, 'custom', 'Y-m-d H:i');
		$form['simplenews']['sending_time']['time'] = array(
				'#type' => 'date_select', '#title' => t('Date'),
				'#default_value' => $time_str,
				'#date_type' => DATE_DATETIME,
				'#date_format' => 'm-d-Y - H:i',
				'#date_timezone' => date_default_timezone_name(),
				'#date_label_position' => 'none',
				'#date_increment' => 1,
				'#date_year_range' => '0:+3',
				'#required' => TRUE,
		);
	}
}


function simplenews_sending_time_submit($form, &$form_state) {
	
	// Get form values from Simplenews.
	$send = $form_state['values']['simplenews']['send'];
	$nid = $form_state['values']['nid'];
	$time = $form_state['values']['simplenews']['sending_time']['time'];
	$time = date_convert($time, DATE_DATETIME, DATE_UNIX, date_default_timezone_name());
	
	db_query("DELETE FROM {simplenews_sending_time} WHERE nid = %d", $nid);
	
	if ($send == SIMPLENEWS_COMMAND_SENDING_TIME) {
		//Set sending time
		$record = array( 'nid' => $nid, 'time' => $time);
		$result = drupal_write_record('simplenews_sending_time', $record);
		if ($result) drupal_set_message(t('Newsletter sending time saved'));
	} 
}


/**
 * Implementation of hook_cron().
 *
 * Essentially we are just checking against a status table
 * and sending pending newsletters.
 *
 */
function simplenews_sending_time_cron() {
	module_load_include('inc', 'simplenews', 'includes/simplenews.mail');
	
	// Get the newsletters pending to send.
	$now_time = $_SERVER['REQUEST_TIME'];
	$result = db_query("SELECT nid FROM {simplenews_sending_time} WHERE sent = 0 AND time <= %d", $now_time);
	
	while ($newsletter = db_fetch_object($result)) {
		// Set newsletter sent status to pending if send by cron.
		db_query("UPDATE {simplenews_newsletters} SET s_status = %d WHERE nid = %d", SIMPLENEWS_STATUS_SEND_PENDING, $newsletter->nid);
		simplenews_send_node($newsletter->nid);
		db_query("UPDATE {simplenews_sending_time} SET sent = 1 WHERE nid = {$newsletter->nid}");
	}
}